---
title: "CorrelationHeatmap"
author: "camryn"
date: "2024-03-08"
output: html_document
---

```{r, libraries}
library(tidyverse)
library(ggpmisc)
library(reshape2)
library(GGally)
library(corrplot)
library(RColorBrewer)
#Run setwd in console
setwd("~/NC-Ecosystem-indicators/data")

my_theme <- function() {theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), plot.title = element_text(size=12, face= "bold", colour= "black"), axis.title.x = element_text(size=12, face="bold", colour = "black"), axis.title.y = element_text(size=12, face="bold", colour = "black"))}
```

#Get all data from a folder
```{r}
data_files <- list.files("~/NC-Ecosystem-indicators/data/finalized/", pattern="*.csv")
for(i in 1:length(data_files)) { 
  assign(paste0(str_extract(data_files[i], '.*(?=\\.csv)')), 
         read.csv(paste0("~/NC-Ecosystem-indicators/data/finalized/",
                         data_files[i])))
}
data_files <- str_extract(data_files, '.*(?=\\.csv)')

#If you wanted to filter files before loading
# turb_files <- data_files[grepl("Turbidity", data_files)]

finalfiles <- data.frame()
for (i in 1:length(data_files)) {
  df <- get(data_files[i])
  if(ncol(df) ==2) {
  colnames(df)[2] <- "Measurement"
  df$Dataset <- data_files[i]
  names(df) <- c("Year", "Measurement", "Dataset")
  finalfiles <- rbind(finalfiles, df)
  }
}

finalfiles$Dataset <- gsub('_finalized', '', finalfiles$Dataset)
finalfiles <- finalfiles %>% pivot_wider(values_from  = "Measurement", names_from = "Dataset")
finalfiles <- mutate_all(finalfiles, function(x) as.numeric(as.character(x)))
```

#Turbidity
```{r}
#Population data import raw
populationdf <- read.csv("~/NC-Ecosystem-indicators/data/SPopulationData1970_SC.csv")
populationdf <- mutate_all(populationdf, function(x) as.numeric(as.character(x)))
populationdf <- populationdf[,-1] 

#Filter for turbidity after importing all
turbidity <- finalfiles[, grep("Turbidity", names(finalfiles)), with = FALSE]
turbidity$Year <- finalfiles$Year
turbidity <- turbidity %>% na.omit()

#Filter for total nitrogen
totalnitrogen <- finalfiles[, grep("TN", names(finalfiles)), with = FALSE]
totalnitrogen$Year <- finalfiles$Year
totalnitrogen <- totalnitrogen %>% na.omit()

```

#Bind together
```{r}
populationdf$Year <- as.numeric(populationdf$Year)
turbidity$Year <- as.numeric(turbidity$Year)
totalnitrogen$Year <- as.numeric(totalnitrogen$Year)
alldata <- merge(totalnitrogen, turbidity,  by = "Year", all = TRUE)
alldata <- merge(alldata, populationdf, by = "Year", all = TRUE)
# alldata <- mutate_all(alldata, function(x) as.numeric(as.character(x)))
alldata <- dplyr::filter(alldata, Year > 1969)
```

#Make correlation matrix
```{r}
corr_mat <- round(stats::cor(alldata, use = "pairwise.complete.obs"),2)
melted_corr_mat <- melt(corr_mat)
```

#Plot this way
```{r}
ggplot(data = melted_corr_mat, aes(x=Var1, y=Var2,fill=value)) +
geom_tile() + scale_fill_gradient(low = "blue", high = "red", na.value = NA) + my_theme() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + labs(title = "Pairwise Correlations", x = "Correlate", y = "Variable", fill = "Coefficient")
```

#Plot this way
```{r}
# M <-cor(alldata, use = "pairwise.complete.obs")
# # png("somepathtoafolder", units="in", width=5, height=5, res=300)
# corrplot(M,  tl.cex = 0.5, type="upper", order="hclust", addCoef.col = 1, number.cex = 0.5, col=brewer.pal(n=8, name="RdYlBu"), title= "Indicators Pairwise Correlations", mar=c(0,0,1,0))
# # dev.off()
```

#Or plot this way
```{r}
 melted_corr_mat %>% ggplot() + geom_tile(mapping = aes(x = Var1, y = Var2, fill = value), size = 1, width = 0.9, height = 0.9) + scale_fill_distiller(palette = "RdBu", limits = c(-1, 1))  + labs(title = "Population and Water Quality Pairwise Correlations", x = "Correlate", y = "Correlate", fill = "Correlation Coefficient") + my_theme() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave("C:/Users/Camryn/Documents/NC-Ecosystem-indicators/figures/NitrogenPopulationTurbidityHeatmap_SC.png", width = 10, height = 8, units = "in")
```



