---
title: "Impacts.responses"
format: html
editor: visual
---

#### Load packages

```{r}
packages <- c("ggplot2", "readxl", "readr", "ggthemes", "GGally", "caret", "dplyr", "ggformula", "ggpmisc", "gt", "ggpubr", "glmtoolbox", "report", "gtools", "tidyr", "car", "lmtest", "chron", "readxl", "stringr", "imputeTS", "lubridate", "mgcv", "ggplot2", "stringr", "devtools")
invisible(lapply(packages, library, character.only= TRUE))

source_gist("https://gist.github.com/gavinsimpson/e73f011fdaaab4bb5a30")

standard_theme <- theme_bw() + theme(panel.border = element_rect(fill=NA, colour = "black")) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + theme(legend.text.align= 0, legend.title= element_text(size = 12), legend.text = element_text(size= 10), axis.text=element_text(size=10), axis.title=element_text(size=12))

setwd("/Users/sallydowd/Documents/GitHub/NC-Ecosystem-indicators")
RecFishing <- read_csv("data/finalized/e1981RecreationalEffortNCSD.csv")
CommLicense <- read_csv("data/finalized/e1994CommercialLicensesNCCB.csv")
VesselLength <- read_csv("data/finalized/e1989CommercialVesselLengthSD.csv")
ClamsLandings <- read_csv("data/finalized/e1994ClamsLandingsNCSD.csv")
OysterLandings <- read_csv("data/finalized/e1994OysterLandingsNCSD.csv")
CommercialTrips <- read_csv("data/finalized/e1994CommercialTripsNCSD.csv")
MenhadenLandings <- read_csv("data/finalized/e1985MenhadenLandingsNCSD.csv")
CommLandings <- read_csv("data/finalized/e1994CommercialLandingsBillNCSD.csv")
BirdNests <- read_csv("data/finalized/b1977BirdNestsNCSD.csv")
CommParts <- read_csv("data/finalized/e1994CommercialParticipantsBillNCSD.csv")
RecCatch <- read_csv("data/finalized/b1981RecreationalTotalCatchNCSD.csv")
RecRelAlive <- read_csv("data/finalized/b1981RecTotalRelAliveNCSD.csv")
ShmpReg <- read_csv("data/finalized/e1994ShrimpRegionNCSD.csv")
BeachNouris <- read_csv("data/finalized/p1939BeachNourishmentSD_finalized.csv")
RecGK <- read_excel("~/Desktop/gulf_kingfish.xlsx")
RecRD <- read_excel("~/Desktop/red_drum.xlsx")
RecSH <- read_excel("~/Desktop/sheepshead.xlsx")
RecSF <- read_excel("~/Desktop/southern_flounder.xlsx")
RecSST <- read_excel("~/Desktop/spotted_seatrout.xlsx")

names(RecFishing) <- tolower(names(RecFishing))
RecFishing <- filter(RecFishing, year < 2020)
names(CommLicense) <- tolower(names(CommLicense))
CommLicense <- filter(CommLicense, between(year, 2000, 2019))
names(VesselLength) <- tolower(names(VesselLength))
VesselLength <- filter(VesselLength, year < 2020)
names(ClamsLandings) <- tolower(names(ClamsLandings))
ClamsLandings <- filter(ClamsLandings, year < 2020)
names(OysterLandings) <- tolower(names(OysterLandings))
OysterLandings <- filter(OysterLandings, year < 2020)
names(CommercialTrips) <- tolower(names(CommercialTrips))
CommercialTrips <- filter(CommercialTrips, year < 2020)
names(MenhadenLandings) <- tolower(names(MenhadenLandings))
MenhadenLandings <- filter(MenhadenLandings, year < 2020)
names(CommLandings) <- tolower(names(CommLandings))
CommLandings <- filter(CommLandings, year < 2020)
names(BirdNests) <- tolower(names(BirdNests))
BirdNests <- filter(BirdNests, year < 2020)
names(CommParts) <- tolower(names(CommParts))
CommParts <- filter(CommParts, year < 2020)
names(RecCatch) <- tolower(names(RecCatch))
RecCatch <- filter(RecCatch, year < 2020)
names(RecRelAlive) <- tolower(names(RecRelAlive))
RecRelAlive <- filter(RecRelAlive, year < 2020)
names(ShmpReg) <- tolower(names(ShmpReg))
ShmpReg <- filter(ShmpReg, year < 2020) %>% select(-...1)
names(BeachNouris) <- tolower(names(BeachNouris))
names(RecGK) <- tolower(names(RecGK))
RecGK <- filter(RecGK, year < 2020) %>% select(year, "total harvest (a+b1)") %>% rename("Total_harvest"= "total harvest (a+b1)")
names(RecRD) <- tolower(names(RecRD))
RecRD <- filter(RecRD, year < 2020) %>% select(year, "total harvest (a+b1)") %>% rename("Total_harvest"= "total harvest (a+b1)")
names(RecSH) <- tolower(names(RecSH))
RecSH <- filter(RecSH, year < 2020) %>% select(year, "total harvest (a+b1)") %>% rename("Total_harvest"= "total harvest (a+b1)")
names(RecSF) <- tolower(names(RecSF))
RecSF <- filter(RecSF, year < 2020) %>% select(year, "total harvest (a+b1)") %>% rename("Total_harvest"= "total harvest (a+b1)")
names(RecSST) <- tolower(names(RecSST))
RecSST <- filter(RecSST, year < 2020) %>% select(year, "total harvest (a+b1)") %>% rename("Total_harvest"= "total harvest (a+b1)")
```

#### Running GAMs for Impacts and Responses Indicators

```{r}
#GAM description
#K value: number of basis functions (k), determines how wiggly the model is, should be between 5 and # of years in dataset, start with 2* number of decades in dataset 
#gam.check output: 
  ##Low p-value (k-index<1) may indicate that k is too low, especially if edf is close to k'. Change k from there and see if p-value increases/k-index, compare k and edf values in addition to looking at p value
#s means smooth
  ##If model doesn't converge than the results are likely not correct (too many parameters in model or not enough data)
  ##small (significant) p values indicate residuals are not randomly distributed (not enough basis functions)
#Plots:
  ##: qqplot comparing model residuals to normal distribution, well fit model residuals will be close to straight line
  ##: histogram of residuals, expect to have symmetric shape
  ##: plot of residual values: should be evenely distributed around 0
  ##: perfect model would form straight line, should cluster around 1:1 line 
```

### GAM diagnostics

```{r}
#Determine k: start with k value from this function
k_det <- function(df){
df1 <- df
((max(df1$year) - max(df1$year) %% 10) - (min(df1$year) - min(df1$year) %% 10))/10 * 2
}

k_det(RecFishing) #6
k_det(CommLicense) #4
k_det(VesselLength) #6
k_det(ClamsLandings) #4
k_det(OysterLandings) #4
k_det(CommercialTrips) #4
k_det(MenhadenLandings) #6
k_det(CommLandings) #4

#Create a GAM - adjust k and remember to check model
gam_diagn <- function(dep_var, k_value, df){
mod <- gam(dep_var ~ s(year, k= k_value), data = df)
print(summary(mod))
gam.check(mod)
}

##Rec fishing 
gam_diagn(RecFishing$angler_trips, 6, RecFishing) #p value not significant 
mod_RecFishing <- gam(angler_trips ~ s(year, k= 6), data = RecFishing)
gam_diagn(RecFishing$angler_trips, 6, RecFishing) #p value not significant 
mod_RecFishing <- gam(angler_trips ~ s(year, k= 6), data = RecFishing)

##Comm License
unique(CommLicense$productname)
#ETS: old commercial license, CFVR: Commercial Fishing Vessel Registration, SCFL: new commercial license-Standard Commercial Fishing License, RSCFL: Retired Standard Commercial Fishing License, Shellfish w/o SCFL: Available to NC residents, allows fishermen to harvest shellfish commercially without having a SCFLE
#These are issued licenses: to get at active fishing effort, we will need to consider a license actively used in fishing (active participant data)

###Dealer
CommLicense_dealer <- CommLicense %>% filter(productname == "Dealer")
k_det(CommLicense_dealer)
gam_diagn(CommLicense_dealer$licenses, 7, CommLicense_dealer) #p value sig. at k= 4, 7 is lowest that looks acceptable
mod_CommLicense_dealer <- gam(licenses ~ s(year, k= 7), data = CommLicense_dealer)

###SCFL: new commercial fishing license
CommLicense_SCFL <- CommLicense %>% filter(productname == "SCFL")
k_det(CommLicense_SCFL)
gam_diagn(CommLicense_SCFL$licenses, 5, CommLicense_SCFL) #p value sig. at k= 2, 5 is lowest where not significant
mod_CommLicense_SCFL <- gam(licenses ~ s(year, k= 5), data = CommLicense_SCFL)

###CFVR
CommLicense_CFVR <- CommLicense %>% filter(productname == "CFVR")
k_det(CommLicense_CFVR)
gam_diagn(CommLicense_CFVR$licenses, 8, CommLicense_CFVR) #p value sig. at k= 2, 8 is lowest that looks acceptable
gam(licenses ~ s(year, k= 8), data = CommLicense_CFVR)
mod_CommLicense_CFVR <- gam(licenses ~ s(year, k= 8), data = CommLicense_CFVR)

###RSCFL
CommLicense_RSCFL <- CommLicense %>% filter(productname == "RSCFL")
k_det(CommLicense_RSCFL) 
gam_diagn(CommLicense_RSCFL$licenses, 6, CommLicense_RSCFL) #p value sig. at k= 2, 6 is lowest that looks acceptable
mod_CommLicense_RSCFL <- gam(licenses ~ s(year, k= 6), data = CommLicense_RSCFL)

###Shellfish w/o SCFL: recheck this 
CommLicense_shellnoSCFL <- CommLicense %>% filter(productname == "Shellfish w/o SCFL")
k_det(CommLicense_shellnoSCFL) 
gam_diagn(CommLicense_shellnoSCFL$licenses, 7, CommLicense_shellnoSCFL) #p value sig. at k= 2, 9 is lowest that looks acceptable
mod_CommLicense_shellnoSCFL <- gam(licenses ~ s(year, k= 7), data = CommLicense_shellnoSCFL)

##Vessel Length
unique(VesselLength$vessellengthrange)
VesselLength <- VesselLength %>% filter(year >= 2000)

VesselLength_18 <- VesselLength %>% filter(vessellengthrange %in% "0-18ft.")
k_det(VesselLength_18)
gam_diagn(VesselLength_18$count, 6, VesselLength_18) #p value not sig. at k= 6 but graphs look bad --> doesn't look great with anything 
mod_VesselLength_18 <- gam(count ~ s(year, k= 6), data = VesselLength_18) 

VesselLength_38 <- VesselLength %>% filter(vessellengthrange %in% "19-38ft.")
k_det(VesselLength_38)
gam_diagn(VesselLength_38$count, 6, VesselLength_38)
mod_VesselLength_38 <- gam(count ~ s(year, k= 6), data = VesselLength_38)

VesselLength_50 <- VesselLength %>% filter(vessellengthrange %in% "39-50ft.")
k_det(VesselLength_50)
gam_diagn(VesselLength_50$count, 6, VesselLength_50)
mod_VesselLength_50 <- gam(count ~ s(year, k= 6), data = VesselLength_50)

VesselLength_over50 <- VesselLength %>% filter(vessellengthrange %in% ">50ft.")
k_det(VesselLength_over50)
gam_diagn(VesselLength_over50$count, 6, VesselLength_over50)
mod_VesselLength_over50 <- gam(count ~ s(year, k= 6), data = VesselLength_over50)

##Clams landings 
ClamsLandings_edt <- ClamsLandings %>% mutate(ratioprpub = private_lbs/public_lbs) %>% select(year, ratioprpub)
k_det(ClamsLandings_edt)
gam_diagn(ClamsLandings_edt$ratioprpub, 7, ClamsLandings_edt) #p value sig. at k= 4, graphs fine at k=7 
mod_ClamsLandings_edt <- gam(ratioprpub ~ s(year, k= 6), data = ClamsLandings_edt)

##Oyster landings
OysterLandings_edt <- OysterLandings %>% mutate(ratioprpub = private_lbs/public_lbs) %>% select(year, ratioprpub)
k_det(OysterLandings_edt)
gam_diagn(OysterLandings_edt$ratioprpub, 8, OysterLandings_edt) #p value sig. at k= 4, graphs fine but not great at k= 8
mod_OysterLandings_edt <- gam(ratioprpub ~ s(year, k= 8), data = OysterLandings_edt)

##Commercial trips: 
CommercialTrips <- CommercialTrips %>% select(year, sum_trips) 
k_det(CommercialTrips)
gam_diagn(CommercialTrips$sum_trips, 6, CommercialTrips) #p value sig. at k= 4, graphs fine at k= 6 
mod_CommercialTrips <- gam(sum_trips ~ s(year, k= 6), data = CommercialTrips)

##Menhaden landings:
MenhadenLandings$species[which(MenhadenLandings$species == "Menhaden bait")] = "Menhaden Bait"
MenhadenLandings$species[which(MenhadenLandings$species == "Menhaden Red")] = "Menhaden Reduction"

###Menhaden Bait: 
MenhadenBait <- MenhadenLandings %>% filter(species == "Menhaden Bait")
k_det(MenhadenBait)
gam_diagn(MenhadenBait$pounds, 6, MenhadenBait) #p value not sig. at k= 6, graphs don't improve that much 
mod_MenhadenBait <- gam(pounds ~ s(year, k= 6), data = MenhadenBait)

###Menhaden Reduction: 
MenhadenReduction <- MenhadenLandings %>% filter(species == "Menhaden Reduction")
k_det(MenhadenReduction)
gam_diagn(MenhadenReduction$pounds, 4, MenhadenReduction) #p value not sig. at k= 4, graphs don't improve that much 
mod_MenhadenReduction <- gam(pounds ~ s(year, k= 4), data = MenhadenReduction)

##Commercial landings
CommLandings$pounds <- as.numeric(CommLandings$pounds)

CommLandings_BayScallop  <- CommLandings %>% filter(species %in% "Bay Scallop")
k_det(CommLandings_BayScallop)
gam_diagn(CommLandings_BayScallop$pounds, 4, CommLandings_BayScallop) #p value not sig. at k= 4, graphs don't improve that much 
mod_CommLandings_BayScallop <- gam(pounds ~ s(year, k= 4), data = CommLandings_BayScallop)

CommLandings_BlueCrab <- CommLandings %>% filter(species %in% "Blue Crab")
k_det(CommLandings_BlueCrab)
gam_diagn(CommLandings_BlueCrab$pounds, 5, CommLandings_BlueCrab) #p value sig. at k= 4
mod_CommLandings_BlueCrab <- gam(pounds ~ s(year, k=  5), data = CommLandings_BlueCrab)

unique(CommLandings_BlueCrab$Year)
CommLandings_HardClams <- CommLandings %>% filter(species %in% "Hard Clams")
k_det(CommLandings_HardClams)
gam_diagn(CommLandings_HardClams$pounds, 6, CommLandings_HardClams) #p value sig. at k= 4, graphs look ok ish
mod_CommLandings_HardClams <- gam(pounds ~ s(year, k=  6), data = CommLandings_HardClams)

CommLandings_Kingfishes  <- CommLandings %>% filter(species %in% "Kingfishes")
k_det(CommLandings_Kingfishes)
gam_diagn(CommLandings_Kingfishes$pounds, 5, CommLandings_Kingfishes) #p value not sig. at 4, graphs look ok
mod_CommLandings_Kingfishes <- gam(pounds ~ s(year, k=  6), data = CommLandings_Kingfishes)

CommLandings_Oysters  <- CommLandings %>% filter(species %in% "Oyster")
k_det(CommLandings_Oysters)
gam_diagn(CommLandings_Oysters$pounds, 7, CommLandings_Oysters) #p value not sig. at 4, graphs best at 7 
mod_CommLandings_Oysters <- gam(pounds ~ s(year, k=  7), data = CommLandings_Oysters)

CommLandings_RedDrum  <- CommLandings %>% filter(species %in% "Red Drum")
k_det(CommLandings_RedDrum)
gam_diagn(CommLandings_RedDrum$pounds, 5, CommLandings_RedDrum) #p value not sig. at 4, graphs fine at 5- not much imrpovement after 
mod_CommLandings_RedDrum <- gam(pounds ~ s(year, k=  5), data = CommLandings_RedDrum)

CommLandings_RiverHerring  <- CommLandings %>% filter(species %in% "River Herring")
k_det(CommLandings_RiverHerring)
gam_diagn(CommLandings_RiverHerring$pounds, 5, CommLandings_RiverHerring) #graphs don't change after 5 much
mod_CommLandings_RiverHerring <- gam(pounds ~ s(year, k=  5), data = CommLandings_RiverHerring)

CommLandings_SouthernFlounder  <- CommLandings %>% filter(species %in% "Southern Flounder")
k_det(CommLandings_SouthernFlounder)
gam_diagn(CommLandings_SouthernFlounder$pounds, 6, CommLandings_SouthernFlounder) #graphs don't change after 5 much
mod_CommLandings_SouthernFlounder <- gam(pounds ~ s(year, k=  6), data = CommLandings_SouthernFlounder)

CommLandings_SpottedSeatrout  <- CommLandings %>% filter(species %in% "Spotted Seatrout")
k_det(CommLandings_SpottedSeatrout)
gam_diagn(CommLandings_SpottedSeatrout$pounds, 4, CommLandings_SpottedSeatrout) 
mod_CommLandings_SpottedSeatrout <- gam(pounds ~ s(year, k=  4), data = CommLandings_SpottedSeatrout)

CommLandings_StripedBass  <- CommLandings %>% filter(species %in% "Striped Bass")
k_det(CommLandings_StripedBass)
gam_diagn(CommLandings_StripedBass$pounds, 6, CommLandings_StripedBass) 
mod_CommLandings_StripedBass <- gam(pounds ~ s(year, k=  6), data = CommLandings_StripedBass)

CommLandings_StripedMullet  <- CommLandings %>% filter(species %in% "Striped Mullet")
k_det(CommLandings_StripedMullet)
gam_diagn(CommLandings_StripedMullet$pounds, 4, CommLandings_StripedMullet) 
mod_CommLandings_StripedMullet <- gam(pounds ~ s(year, k=  4), data = CommLandings_StripedMullet)

CommLandings_BrownShrimp  <- CommLandings %>% filter(species %in% "Shrimp, Brown")
k_det(CommLandings_BrownShrimp)
gam_diagn(CommLandings_BrownShrimp$pounds, 4, CommLandings_BrownShrimp) #response vs. fitted doesn't look good no matter the k value 
mod_CommLandings_BrownShrimp <- gam(pounds ~ s(year, k=  4), data = CommLandings_BrownShrimp)

CommLandings_PinkShrimp  <- CommLandings %>% filter(species %in% "Shrimp, Pink")
k_det(CommLandings_PinkShrimp)
gam_diagn(CommLandings_PinkShrimp$pounds, 4, CommLandings_PinkShrimp) #p value not significant, graphs look bad no matter the k value 
mod_CommLandings_PinkShrimp <- gam(pounds ~ s(year, k=  4), data = CommLandings_PinkShrimp)

CommLandings_WhiteShrimp  <- CommLandings %>% filter(species %in% "Shrimp, White")
k_det(CommLandings_WhiteShrimp)
gam_diagn(CommLandings_WhiteShrimp$pounds, 6, CommLandings_WhiteShrimp) #normality graphs acceptable at this p value
mod_CommLandings_WhiteShrimp <- gam(pounds ~ s(year, k=  6), data = CommLandings_WhiteShrimp)

##Birds
BirdNests <- BirdNests %>% select(year, sum_nests)
k_det(BirdNests)
gam_diagn(BirdNests$sum_nests, 8, BirdNests) #assumptions aren't met but doesn't get better with k 
mod_BirdNests <- gam(sum_nests ~ s(year, k=  8), data = BirdNests)

##Commercial participants 
CommParts <- CommParts %>% select(year, species, participants)
unique(CommParts$species)

CommParts_BayScallop <- CommParts %>% filter(species %in% "Bay Scallop")
k_det(CommParts_BayScallop)
gam_diagn(CommParts_BayScallop$participants, 4, CommParts_BayScallop) #doesn't improve 
mod_CommParts_BayScallop <- gam(participants ~ s(year, k=  4), data = CommParts_BayScallop)

CommParts_BlueCrab <- CommParts %>% filter(species %in% "Blue Crab")
k_det(CommParts_BlueCrab)
gam_diagn(CommParts_BlueCrab$participants, 9, CommParts_BlueCrab) #p value sig at 4-8 but then residuals get more non-normally distributed 
mod_CommParts_BlueCrab <- gam(participants ~ s(year, k=  9), data = CommParts_BlueCrab)

CommParts_HardClams <- CommParts %>% filter(species %in% "Hard Clams")
k_det(CommParts_HardClams)
gam_diagn(CommParts_HardClams$participants, 8, CommParts_HardClams) #p value sig at 4-7 but then residuals get more non-normally distributed 
mod_CommParts_HardClams <- gam(participants ~ s(year, k=  8), data = CommParts_HardClams)

CommParts_Kingfishes <- CommParts %>% filter(species %in% "Kingfishes")
k_det(CommParts_Kingfishes)
gam_diagn(CommParts_Kingfishes$participants, 4, CommParts_Kingfishes) #p value not sig. at 4, graphs don't get that much better 
mod_CommParts_Kingfishes <- gam(participants ~ s(year, k= 4), data = CommParts_Kingfishes)

CommParts_Oyster <- CommParts %>% filter(species %in% "Oyster")
k_det(CommParts_Oyster)
gam_diagn(CommParts_Oyster$participants, 4, CommParts_Oyster) #p value not sig. at 4, graphs don't get that much better 
mod_CommParts_Oyster <- gam(participants ~ s(year, k= 4), data = CommParts_Oyster)

CommParts_RedDrum <- CommParts %>% filter(species %in% "Red Drum")
k_det(CommParts_RedDrum)
gam_diagn(CommParts_RedDrum$participants, 4, CommParts_RedDrum) #p value not sig. at 4, graphs don't get that much better 
mod_CommParts_RedDrum <- gam(participants ~ s(year, k= 4), data = CommParts_RedDrum)

CommParts_RiverHerring <- CommParts %>% filter(species %in% "River Herring")
k_det(CommParts_RiverHerring)
gam_diagn(CommParts_RiverHerring$participants, 4, CommParts_RiverHerring) #p value not sig. at 4 and graphs look good
mod_CommParts_RiverHerring <- gam(participants ~ s(year, k= 4), data = CommParts_RiverHerring)

CommParts_SouthernFlounder <- CommParts %>% filter(species %in% "Southern Flounder")
k_det(CommParts_SouthernFlounder)
gam_diagn(CommParts_SouthernFlounder$participants, 5, CommParts_SouthernFlounder) #p value sig. at 4
mod_CommParts_SouthernFlounder <- gam(participants ~ s(year, k= 5), data = CommParts_SouthernFlounder)

CommParts_SpottedSeatrout <- CommParts %>% filter(species %in% "Spotted Seatrout")
k_det(CommParts_SpottedSeatrout)
gam_diagn(CommParts_SpottedSeatrout$participants, 4, CommParts_SpottedSeatrout) #p value not sig. at 4, graphs don't get that much better 
mod_CommParts_SpottedSeatrout <- gam(participants ~ s(year, k= 4), data = CommParts_SpottedSeatrout)

CommParts_StripedBass <- CommParts %>% filter(species %in% "Striped Bass")
k_det(CommParts_StripedBass)
gam_diagn(CommParts_StripedBass$participants, 7, CommParts_StripedBass) #p value not sig. at 4, graphs look best at 7 
mod_CommParts_StripedBass <- gam(participants ~ s(year, k= 7), data = CommParts_StripedBass)

CommParts_StripedMullet <- CommParts %>% filter(species %in% "Striped Mullet")
k_det(CommParts_StripedMullet)
gam_diagn(CommParts_StripedMullet$participants, 5, CommParts_StripedMullet) #small sig at 4 
mod_CommParts_StripedMullet <- gam(participants ~ s(year, k= 5), data = CommParts_StripedMullet)

CommParts_BrownShrimp <- CommParts %>% filter(species %in% "Shrimp, Brown")
k_det(CommParts_BrownShrimp)
gam_diagn(CommParts_BrownShrimp$participants, 6, CommParts_BrownShrimp) #k= 6 looks best
mod_CommParts_BrownShrimp <- gam(participants ~ s(year, k= 6), data = CommParts_BrownShrimp)

CommParts_PinkShrimp <- CommParts %>% filter(species %in% "Shrimp, Pink")
k_det(CommParts_PinkShrimp)
gam_diagn(CommParts_PinkShrimp$participants, 4, CommParts_PinkShrimp) #graphs don't improve after k=4 
mod_CommParts_PinkShrimp <- gam(participants ~ s(year, k= 4), data = CommParts_PinkShrimp)

CommParts_WhiteShrimp <- CommParts %>% filter(species %in% "Shrimp, White")
k_det(CommParts_WhiteShrimp)
gam_diagn(CommParts_WhiteShrimp$participants, 4, CommParts_WhiteShrimp) #graphs don't improve after k=4 
mod_CommParts_WhiteShrimp <- gam(participants ~ s(year, k= 4), data = CommParts_WhiteShrimp)

##Rec Catch
k_det(RecCatch)
gam_diagn(RecCatch$sum_catch, 8, RecCatch) #p sig at k= 6 and lower at k= 7 
mod_RecCatch <- gam(sum_catch ~ s(year, k= 8), data = RecCatch)

##Rec Rel Alive
k_det(RecRelAlive)
gam_diagn(RecRelAlive$relalive, 6, RecRelAlive) #p not sig at k= 6, graphs don't get much better 
mod_RecRelAlive <- gam(relalive ~ s(year, k= 6), data = RecRelAlive)

##Rec Rel Alive reduced
RecRelAliveRed <- RecRelAlive %>% filter(year > 1986)
k_det(RecRelAliveRed)
gam_diagn(RecRelAliveRed$relalive, 6, RecRelAliveRed) #p not sig at k= 6
mod_RecRelAliveRed <- gam(relalive ~ s(year, k= 6), data = RecRelAliveRed)

##Shrimp Region Participants
##Northern:
k_det(ShmpReg)
ShmpRegPartN <- ShmpReg %>% filter(region %in% "Northern")
gam_diagn(ShmpRegPartN$sum_participants, 4, ShmpRegPartN) #p not sig at k= 4, figures don't improve
mod_ShmpRegPartN <- gam(sum_participants ~ s(year, k= 4), data = ShmpRegPartN)

##Central:
ShmpRegPartC <- ShmpReg %>% filter(region %in% "Central")
gam_diagn(ShmpRegPartC$sum_participants, 4, ShmpRegPartC) #p not sig at k= 4, figures don't improve
mod_ShmpRegPartC <- gam(sum_participants ~ s(year, k= 4), data = ShmpRegPartC)

##Core Banks: 
ShmpRegPartCB <- ShmpReg %>% filter(region %in% "Core Banks")
gam_diagn(ShmpRegPartCB$sum_participants, 6, ShmpRegPartCB) #p sig. at k=4, looks better at k= 6 
mod_ShmpRegPartCB <- gam(sum_participants ~ s(year, k= 6), data = ShmpRegPartCB)

##Southern: 
ShmpRegPartS <- ShmpReg %>% filter(region %in% "Southern")
gam_diagn(ShmpRegPartS$sum_participants, 4, ShmpRegPartS) #p not sig at k= 4, figures don't improve
mod_ShmpRegPartS <- gam(sum_participants ~ s(year, k= 4), data = ShmpRegPartS)

##Shrimp Region Pounds 
k_det(ShmpReg)
gam_diagn(ShmpReg$sum_pounds, 7, ShmpReg) #p not sig at k= 4 and graphs don't imrpove
mod_ShmpRegLbs <- gam(sum_pounds ~ s(year, k= 4), data = ShmpReg)

##Beach Nourishment: cost
k_det(BeachNouris) #10
##Northern
BeachNourisN <- BeachNouris %>% filter(region %in% "Northern")
gam_diagn(BeachNourisN$sum_cost, 10, BeachNourisN)
mod_BeachNourisN<- gam(sum_cost ~ s(year, k= 10), data = BeachNourisN)

##Central
BeachNourisC <- BeachNouris %>% filter(region %in% "Central")
gam_diagn(BeachNourisC$sum_cost, 10, BeachNourisC)
mod_BeachNourisC<- gam(sum_cost ~ s(year, k= 10), data = BeachNourisC)

##Southern 
BeachNourisS <- BeachNouris %>% filter(region %in% "Southern")
gam_diagn(BeachNourisS$sum_cost, 10, BeachNourisN)
mod_BeachNourisS <- gam(sum_cost ~ s(year, k= 10), data = BeachNourisS)

##Beach Nourishment: Volume
k_det(BeachNouris) #10
##Northern
BeachNourisNvol <- BeachNouris %>% filter(region %in% "Northern")
gam_diagn(BeachNourisNvol$sum_vol, 10, BeachNourisNvol)
mod_BeachNourisNvol <- gam(sum_vol ~ s(year, k= 10), data = BeachNourisNvol)

##Central
BeachNourisCvol <- BeachNouris %>% filter(region %in% "Central")
gam_diagn(BeachNourisCvol$sum_vol, 10, BeachNourisCvol)
mod_BeachNourisCvol <- gam(sum_vol ~ s(year, k= 10), data = BeachNourisCvol)

##Southern 
BeachNourisSvol <- BeachNouris %>% filter(region %in% "Southern")
gam_diagn(BeachNourisSvol$sum_vol, 10, BeachNourisNvol)
mod_BeachNourisSvol <- gam(sum_vol ~ s(year, k= 10), data = BeachNourisSvol)

##Rec fishing by Species
###Gulf kingfish
gam_diagn(RecGK$Total_harvest, 6, RecGK)
mod_RecGK <- gam(Total_harvest ~ s(year, k= 6), data = RecGK)

###Red drum 
gam_diagn(RecRD$Total_harvest, 6, RecRD)
mod_RecRD <- gam(Total_harvest ~ s(year, k= 6), data = RecRD)

####Red drum, modified
RecRD.m <- RecRD %>% filter(year > 1990)
gam_diagn(RecRD.m$Total_harvest, 6, RecRD.m)
mod_RecRD.m <- gam(Total_harvest ~ s(year, k= 6), data = RecRD.m)

###Sheepshead
gam_diagn(RecSH$Total_harvest, 6, RecSH)
mod_RecSH <- gam(Total_harvest ~ s(year, k= 6), data = RecSH)

###Southern flounder
gam_diagn(RecSF$Total_harvest, 6, RecSF)
mod_RecSF <- gam(Total_harvest ~ s(year, k= 6), data = RecSF)

###Spotted seatrout 
gam_diagn(RecSST$Total_harvest, 6, RecSST)
mod_RecSST <- gam(Total_harvest ~ s(year, k= 6), data = RecSST)
```

#### GAM Functions: Results

```{r}
GAM_predict_p2mod <- function(df, mod_df){
pdata <- with(df, data.frame(year = year)) #year only
p2_mod <- predict(mod_df, newdata = pdata,  type = "terms", se.fit = TRUE) #returns matrix giving predictions for each of requested model terms
intercept = as.numeric(attr(p2_mod,"constant")) 
return(p2_mod)
}

GAM_predict_pdata <- function(df, mod_df){
pdata <- with(df, data.frame(year = year)) #year only
p2_mod <- predict(mod_df, newdata = pdata,  type = "terms", se.fit = TRUE) #returns matrix giving predictions for each of requested model terms
intercept = as.numeric(attr(p2_mod,"constant")) # look at p2_mod and extract the intercept
pdata <- transform(pdata, p2_mod = p2_mod$fit[,1], se2 = p2_mod$se.fit[,1])
return(pdata)
}


GAM_deriv <- function(pdata, mod_df){
Term = "year"
n <- as.numeric(length(unique(pdata$year)))
mod.d <- Deriv(mod_df, n=n) # n is the number of years
mod.dci <- confint(mod.d, term = Term)
mod.dsig <- signifD(pdata$p2_mod, d = mod.d[[Term]]$deriv, upper = mod.dci[[Term]]$upper, lower = mod.dci[[Term]]$lower)
return(mod.dsig)
}
```

#### GAM Functions: figures

```{r}
#Run this if your significant total trend, non significant post 1997 
long_sig <- function(df, dep_var, intercept, pdata, mod.dsig, y_units, x_units, title_name){
ggplot() + 
  geom_line(data = df, aes(x = year, y = dep_var), color = 'grey53', alpha = 0.6) +
  geom_point(data = df, aes(x = year, y = dep_var), color = 'gray53', alpha = 0.6) + 
  geom_line(data=pdata, aes(x = year, y = p2_mod+intercept), se = FALSE, color = 'black', linetype = 'twodash', size = 1) + 
  geom_line(data = pdata, aes(y = unlist(mod.dsig$incr)+intercept, x = year), color = "#0072B2", size = 1) +  
  geom_line(data = pdata, aes(y = unlist(mod.dsig$decr)+intercept, x = year), color = '#D55E00', size = 1) +
   geom_smooth(data = df, aes(x = year, y = dep_var), method = lm, se = FALSE, color = "gray", alpha = 0.2) +
  theme_bw() +
  labs (y = y_units, x = x_units, title = paste0(title_name)) + 
  theme(plot.title=element_text(size = 16,face = 'bold',hjust = 0.5), axis.title=element_text(size = 14, face = 'bold'), axis.text= element_text(color = 'black', size = 12)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
}

#Run this if your non significant total trend, significant post 1997
short_sig <- function(df, dep_var, intercept, pdata, mod.dsig, dfpost1997, dep_var1997, y_units, x_units, title_name){
ggplot() + 
  geom_line(data = df, aes(x = year, y = dep_var), color = 'grey53', alpha = 0.6) +
  geom_point(data = df, aes(x = year, y = dep_var), color = 'gray53', alpha = 0.6) + 
  geom_line(data=pdata, aes(x = year, y = p2_mod+intercept), se = FALSE, color = 'black', linetype = 'twodash', size = 1) + 
  geom_line(data = pdata, aes(y = unlist(mod.dsig$incr)+intercept, x = year), color = "#0072B2", size = 1) +  
  geom_line(data = pdata, aes(y = unlist(mod.dsig$decr)+intercept, x = year), color = '#D55E00', size = 1) + 
  geom_smooth(data = dfpost1997, aes(x = year, y = dep_var1997), method = lm, se = FALSE, color = "#009E73") +
  theme_bw() +
  labs (y = y_units, x = x_units, title = paste0(title_name)) + 
  theme(plot.title=element_text(size = 16,face = 'bold',hjust = 0.5), axis.title=element_text(size = 14, face = 'bold'), axis.text= element_text(color = 'black', size = 12)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
}

##Run this if your significant total trend, and significant post 1997
both_sig <- function(df, dep_var, intercept, pdata, mod.dsig, dfpost1997, dep_var1997, y_units, x_units, title_name){
ggplot() + 
  geom_line(data = df, aes(x = year, y = dep_var), color = 'grey53', alpha = 0.6) +
  geom_point(data = df, aes(x = year, y = dep_var), color = 'gray53', alpha = 0.6) + 
  geom_line(data=pdata, aes(x = year, y = p2_mod+intercept), se = FALSE, color = 'black', linetype = 'twodash', size = 1) + geom_line(data = pdata, aes(y = unlist(mod.dsig$incr)+intercept, x = year), color = "#0072B2", size = 1) + geom_line(data = pdata, aes(y = unlist(mod.dsig$decr)+intercept, x = year), color = "#D55E00", size = 1) +   geom_smooth(data = dfpost1997, aes(x = year, y = dep_var1997), method = lm, se = FALSE, color = "#009E73") +
   geom_smooth(data = df, aes(x = year, y = dep_var), method = lm, se = FALSE, color = "gray", alpha = 0.2) +
  theme_bw() +
  labs (y = y_units, x = x_units, title = paste0(title_name)) + 
  theme(plot.title=element_text(size = 16,face = 'bold',hjust = 0.5), axis.title=element_text(size = 14, face = 'bold'), axis.text= element_text(color = 'black', size = 12)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
}


##Run this if non significant total trend, and non significant post 1997
both_nonsig <- function(df, dep_var, intercept, pdata, mod.dsig, y_units, x_units, title_name){
ggplot() + 
  geom_line(data = df, aes(x = year, y = dep_var), color = 'grey53', alpha = 0.6) +
  geom_point(data = df, aes(x = year, y = dep_var), color = 'gray53', alpha = 0.6) + 
  geom_line(data=pdata, aes(x = year, y = p2_mod+intercept), se = FALSE, color = 'black', linetype = 'twodash', size = 1) + 
  geom_line(data = pdata, aes(y = unlist(mod.dsig$incr)+intercept, x = year), color = "#0072B2", size = 1) + 
  geom_line(data = pdata, aes(y = unlist(mod.dsig$decr)+intercept, x = year), color = "#D55E00", size = 1) + 
  theme_bw() +
  labs (y = y_units, x = x_units, title = paste0(title_name)) + 
  theme(plot.title=element_text(size = 16,face = 'bold',hjust = 0.5), axis.title=element_text(size = 14, face = 'bold'), axis.text= element_text(color = 'black', size = 12)) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())
}

```

#### Gam Results

```{r}
#RecFishing
p2mod_RecFishing <- GAM_predict_p2mod(RecFishing, mod_RecFishing)
intercept_RecFishing = as.numeric(attr(p2mod_RecFishing,"constant")) 
pdata_RecFishing <- GAM_predict_pdata(RecFishing, mod_RecFishing)
mod.dsig_RecFishing <- GAM_deriv(pdata_RecFishing, mod_RecFishing)
linearMod<- lm(angler_trips ~ year, data= RecFishing)
summary(linearMod)
dfpost1997_RecFishing <- filter(RecFishing, year > 1997)
linearMod_1997<- lm(angler_trips ~ year, data=dfpost1997)
summary(linearMod_1997)
both_sig(RecFishing, RecFishing$angler_trips, intercept_RecFishing, pdata_RecFishing, mod.dsig_RecFishing, dfpost1997_RecFishing, dfpost1997_RecFishing$angler_trips, "Number of Angler Trips", "Year", "Number of Recreational Angler Trips")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "RecFishingGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Comm License
##Dealer: not working! 
p2mod_CommLicense_dealer <- GAM_predict_p2mod(CommLicense_dealer, mod_CommLicense_dealer)
intercept_CommLicense_dealer = as.numeric(attr(p2mod_CommLicense_dealer,"constant")) 
pdata_CommLicense_dealer <- GAM_predict_pdata(CommLicense_dealer, mod_CommLicense_dealer)
mod.dsig_CommLicense_dealer <- GAM_deriv(pdata_CommLicense_dealer, mod_CommLicense_dealer)
linearMod <- lm(licenses ~ year, data= CommLicense_dealer)
summary(linearMod)
dfpost1997_CommLicense_dealer <- filter(CommLicense_dealer, year > 1997)
linearMod_1997<- lm(licenses ~ year, data=dfpost1997_CommLicense_dealer)
summary(linearMod_1997)
both_sig(CommLicense_dealer, CommLicense_dealer$licenses, intercept_CommLicense_dealer, pdata_CommLicense_dealer, mod.dsig_CommLicense_dealer, dfpost1997_CommLicense_dealer, dfpost1997_CommLicense_dealer$licenses, "Number of Dealer Licenses", "Year", "Number of Dealer Licenses")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLicenseDealerGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##SCFL
p2mod_CommLicense_SCFL <- GAM_predict_p2mod(CommLicense_SCFL, mod_CommLicense_SCFL)
intercept_CommLicense_SCFL = as.numeric(attr(p2mod_CommLicense_SCFL,"constant")) 
pdata_CommLicense_SCFL <- GAM_predict_pdata(CommLicense_SCFL, mod_CommLicense_SCFL)
mod.dsig_CommLicense_SCFL <- GAM_deriv(pdata_CommLicense_SCFL, mod_CommLicense_SCFL)
linearMod <- lm(licenses ~ year, data= CommLicense_SCFL)
summary(linearMod)
dfpost1997_CommLicense_SCFL <- filter(CommLicense_SCFL, year > 1997)
linearMod_1997 <- lm(licenses ~ year, data=dfpost1997_SCFL)
summary(linearMod_1997)
both_sig(CommLicense_SCFL, CommLicense_SCFL$licenses, intercept_CommLicense_SCFL, pdata_CommLicense_SCFL, mod.dsig_CommLicense_SCFL, dfpost1997_CommLicense_SCFL, dfpost1997_CommLicense_SCFL$licenses, "Number of SCFL Licenses", "Year", "Number of Standard Commercial Fishing Licenses")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLicenseSCFLGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##CFVR 
p2mod_CommLicense_CFVR <- GAM_predict_p2mod(CommLicense_CFVR, mod_CommLicense_CFVR)
intercept_CommLicense_CFVR = as.numeric(attr(p2mod_CommLicense_CFVR,"constant")) 
pdata_CommLicense_CFVR <- GAM_predict_pdata(CommLicense_CFVR, mod_CommLicense_CFVR)
mod.dsig_CommLicense_CFVR <- GAM_deriv(pdata_CommLicense_CFVR, mod_CommLicense_CFVR)
linearMod <- lm(licenses ~ year, data= CommLicense_CFVR)
summary(linearMod)
dfpost1997_CommLicense_CFVR <- filter(CommLicense_CFVR, year > 1997)
linearMod_1997 <- lm(licenses ~ year, data=dfpost1997_CommLicense_CFVR)
summary(linearMod_1997)
both_sig(CommLicense_CFVR, CommLicense_CFVR$licenses, intercept_CommLicense_CFVR, pdata_CommLicense_CFVR, mod.dsig_CommLicense_CFVR, dfpost1997_CommLicense_CFVR, dfpost1997_CommLicense_CFVR$licenses, "Number of CFVR Licenses", "Year", "Number of Commercial Fishing Vessel\n Registration Licenses")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLicenseCFVRGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##RSCFL
p2mod_CommLicense_RSCFL <- GAM_predict_p2mod(CommLicense_RSCFL, mod_CommLicense_RSCFL)
intercept_CommLicense_RSCFL = as.numeric(attr(p2mod_CommLicense_RSCFL,"constant")) 
pdata_CommLicense_RSCFL <- GAM_predict_pdata(CommLicense_RSCFL, mod_CommLicense_RSCFL)
mod.dsig_CommLicense_RSCFL <- GAM_deriv(pdata_CommLicense_RSCFL, mod_CommLicense_RSCFL)
linearMod <- lm(licenses ~ year, data= CommLicense_RSCFL)
summary(linearMod)
dfpost1997_CommLicense_RSCFL <- filter(CommLicense_RSCFL, year > 1997)
linearMod_1997 <- lm(licenses ~ year, data=dfpost1997_CommLicense_RSCFL)
summary(linearMod_1997)
both_sig(CommLicense_RSCFL, CommLicense_RSCFL$licenses, intercept_CommLicense_RSCFL, pdata_CommLicense_RSCFL, mod.dsig_CommLicense_RSCFL, dfpost1997_CommLicense_RSCFL, dfpost1997_CommLicense_RSCFL$licenses, "Number of RSCFL Licenses", "Year", "Number of Retired Standard Commercial\n  Fishing Licenses")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLicenseRSCFLGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Shellfish w/o SCFL 
p2mod_CommLicense_shellnoSCFL <- GAM_predict_p2mod(CommLicense_shellnoSCFL, mod_CommLicense_shellnoSCFL)
intercept_CommLicense_shellnoSCFL = as.numeric(attr(p2mod_CommLicense_shellnoSCFL,"constant")) 
pdata_CommLicense_shellnoSCFL <- GAM_predict_pdata(CommLicense_shellnoSCFL, mod_CommLicense_shellnoSCFL)
mod.dsig_CommLicense_shellnoSCFL <- GAM_deriv(pdata_CommLicense_shellnoSCFL, mod_CommLicense_shellnoSCFL)
linearMod <- lm(licenses ~ year, data= CommLicense_shellnoSCFL)
summary(linearMod)
dfpost1997_CommLicense_shellnoSCFL <- filter(CommLicense_shellnoSCFL, year > 1997)
linearMod_1997 <- lm(licenses ~ year, data=dfpost1997_CommLicense_shellnoSCFL)
summary(linearMod_1997)
both_sig(CommLicense_shellnoSCFL, CommLicense_shellnoSCFL$licenses, intercept_CommLicense_shellnoSCFL, pdata_CommLicense_shellnoSCFL, mod.dsig_CommLicense_shellnoSCFL, dfpost1997_CommLicense_shellnoSCFL, dfpost1997_CommLicense_shellnoSCFL$licenses, "Number of Shellfish Licenses (no SCFL)", "Year", "Number of Shellfish Licenses\n  without a SCFL")
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLicenseshellnoSCFLGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Vessel length
##0-18 ft.
p2mod_VesselLength_18 <- GAM_predict_p2mod(VesselLength_18, mod_VesselLength_18)
intercept_VesselLength_18 = as.numeric(attr(p2mod_VesselLength_18,"constant")) 
pdata_VesselLength_18 <- GAM_predict_pdata(VesselLength_18, mod_VesselLength_18)
mod.dsig_VesselLength_18 <- GAM_deriv(pdata_VesselLength_18, mod_VesselLength_18)
linearMod <- lm(count ~ year, data= VesselLength_18)
summary(linearMod)
dfpost1997_VesselLength_18 <- filter(VesselLength_18, year > 1997)
linearMod_1997 <- lm(count ~ year, data=dfpost1997_VesselLength_18)
summary(linearMod_1997)
both_sig(VesselLength_18, VesselLength_18$count, intercept_VesselLength_18, pdata_VesselLength_18, mod.dsig_VesselLength_18, dfpost1997_VesselLength_18, dfpost1997_VesselLength_18$count, "Number of Vessels", "Year", "Number of Vessels 0-18ft.") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "VesselLength_18GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##19-38 ft. 
p2mod_VesselLength_38 <- GAM_predict_p2mod(VesselLength_38, mod_VesselLength_38)
intercept_VesselLength_38 = as.numeric(attr(p2mod_VesselLength_38,"constant")) 
pdata_VesselLength_38 <- GAM_predict_pdata(VesselLength_38, mod_VesselLength_38)
mod.dsig_VesselLength_38 <- GAM_deriv(pdata_VesselLength_38, mod_VesselLength_38)
linearMod <- lm(count ~ year, data= VesselLength_38)
summary(linearMod)
dfpost1997_VesselLength_38 <- filter(VesselLength_38, year > 1997)
linearMod_1997 <- lm(count ~ year, data=dfpost1997_VesselLength_38)
summary(linearMod_1997)
both_sig(VesselLength_38, VesselLength_38$count, intercept_VesselLength_38, pdata_VesselLength_38, mod.dsig_VesselLength_38, dfpost1997_VesselLength_38, dfpost1997_VesselLength_38$count, "Number of Vessels", "Year", "Number of Vessels 19-38 ft.") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "VesselLength_38GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##39-50 ft. 
p2mod_VesselLength_50 <- GAM_predict_p2mod(VesselLength_50, mod_VesselLength_50)
intercept_VesselLength_50 = as.numeric(attr(p2mod_VesselLength_50,"constant")) 
pdata_VesselLength_50 <- GAM_predict_pdata(VesselLength_50, mod_VesselLength_50)
mod.dsig_VesselLength_50 <- GAM_deriv(pdata_VesselLength_50, mod_VesselLength_50)
linearMod <- lm(count ~ year, data= VesselLength_50)
summary(linearMod)
dfpost1997_VesselLength_50 <- filter(VesselLength_50, year > 1997)
linearMod_1997 <- lm(count ~ year, data=dfpost1997_VesselLength_50)
summary(linearMod_1997)
both_sig(VesselLength_50, VesselLength_50$count, intercept_VesselLength_50, pdata_VesselLength_50, mod.dsig_VesselLength_50, dfpost1997_VesselLength_50, dfpost1997_VesselLength_50$count, "Number of Vessels", "Year", "Number of Vessels 39-50 ft.") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "VesselLength_50GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##over 50 ft
p2mod_VesselLength_over50 <- GAM_predict_p2mod(VesselLength_over50, mod_VesselLength_over50)
intercept_VesselLength_over50 = as.numeric(attr(p2mod_VesselLength_over50,"constant")) 
pdata_VesselLength_over50 <- GAM_predict_pdata(VesselLength_over50, mod_VesselLength_over50)
mod.dsig_VesselLength_over50 <- GAM_deriv(pdata_VesselLength_over50, mod_VesselLength_over50)
linearMod <- lm(count ~ year, data= VesselLength_over50)
summary(linearMod)
dfpost1997_VesselLength_over50 <- filter(VesselLength_over50, year > 1997)
linearMod_1997 <- lm(count ~ year, data=dfpost1997_VesselLength_over50)
summary(linearMod_1997)
both_sig(VesselLength_over50, VesselLength_over50$count, intercept_VesselLength_over50, pdata_VesselLength_over50, mod.dsig_VesselLength_over50, dfpost1997_VesselLength_over50, dfpost1997_VesselLength_over50$count, "Number of Vessels", "Year", "Number of Vessels over 50 ft.") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "VesselLength_over50GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Clams landings 
p2mod_ClamsLandings_edt <- GAM_predict_p2mod(ClamsLandings_edt, mod_ClamsLandings_edt)
intercept_ClamsLandings_edt = as.numeric(attr(p2mod_ClamsLandings_edt,"constant")) 
pdata_ClamsLandings_edt <- GAM_predict_pdata(ClamsLandings_edt, mod_ClamsLandings_edt)
mod.dsig_ClamsLandings_edt <- GAM_deriv(pdata_ClamsLandings_edt, mod_ClamsLandings_edt)
linearMod <- lm(ratioprpub ~ year, data= ClamsLandings_edt)
summary(linearMod)
dfpost1997_ClamsLandings_edt <- filter(ClamsLandings_edt, year > 1997)
linearMod_1997 <- lm(ratioprpub ~ year, data=dfpost1997_ClamsLandings_edt)
summary(linearMod_1997)
both_sig(ClamsLandings_edt, ClamsLandings_edt$ratioprpub, intercept_ClamsLandings_edt, pdata_ClamsLandings_edt, mod.dsig_ClamsLandings_edt, dfpost1997_ClamsLandings_edt, dfpost1997_ClamsLandings_edt$ratioprpub, "Private:Public Harvest (lbs)", "Year", "Ratio of Clams Harvested with Private\n vs. Public Lease") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "ClamsLandings_edtGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Oyster landings
p2mod_OysterLandings_edt <- GAM_predict_p2mod(OysterLandings_edt, mod_OysterLandings_edt)
intercept_OysterLandings_edt = as.numeric(attr(p2mod_OysterLandings_edt,"constant")) 
pdata_OysterLandings_edt <- GAM_predict_pdata(OysterLandings_edt, mod_OysterLandings_edt)
mod.dsig_OysterLandings_edt <- GAM_deriv(pdata_OysterLandings_edt, mod_OysterLandings_edt)
linearMod <- lm(ratioprpub ~ year, data= OysterLandings_edt)
summary(linearMod)
dfpost1997_OysterLandings_edt <- filter(OysterLandings_edt, year > 1997)
linearMod_1997 <- lm(ratioprpub ~ year, data=dfpost1997_OysterLandings_edt)
summary(linearMod_1997)
both_sig(OysterLandings_edt, OysterLandings_edt$ratioprpub, intercept_OysterLandings_edt, pdata_OysterLandings_edt, mod.dsig_OysterLandings_edt, dfpost1997_OysterLandings_edt, dfpost1997_OysterLandings_edt$ratioprpub, "Private:Public Harvest (lbs)", "Year", "Ratio of Oysters Harvested with Private\n vs. Public Lease") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "OysterLandings_edtGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Commercial trips: 
p2mod_CommercialTrips <- GAM_predict_p2mod(CommercialTrips, mod_CommercialTrips)
intercept_CommercialTrips = as.numeric(attr(p2mod_CommercialTrips,"constant")) 
pdata_CommercialTrips <- GAM_predict_pdata(CommercialTrips, mod_CommercialTrips)
mod.dsig_CommercialTrips <- GAM_deriv(pdata_CommercialTrips, mod_CommercialTrips)
linearMod <- lm(sum_trips ~ year, data= CommercialTrips)
summary(linearMod)
dfpost1997_CommercialTrips <- filter(CommercialTrips, year > 1997)
linearMod_1997 <- lm(sum_trips ~ year, data=dfpost1997_CommercialTrips)
summary(linearMod_1997)
both_sig(CommercialTrips, CommercialTrips$sum_trips, intercept_CommercialTrips, pdata_CommercialTrips, mod.dsig_CommercialTrips, dfpost1997_CommercialTrips, dfpost1997_CommercialTrips$sum_trips, "Number of Trips", "Year", "Number of Commercial Trips") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommercialTripsGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Commercial landings
##Bay Scallop 

p2mod_CommLandings_BayScallop <- GAM_predict_p2mod(CommLandings_BayScallop, mod_CommLandings_BayScallop)
intercept_CommLandings_BayScallop = as.numeric(attr(p2mod_CommLandings_BayScallop,"constant")) 
pdata_CommLandings_BayScallop <- GAM_predict_pdata(CommLandings_BayScallop, mod_CommLandings_BayScallop)
mod.dsig_CommLandings_BayScallop <- GAM_deriv(pdata_CommLandings_BayScallop, mod_CommLandings_BayScallop)
linearMod <- lm(pounds ~ year, data= CommLandings_BayScallop)
summary(linearMod)
dfpost1997_CommLandings_BayScallop <- filter(CommLandings_BayScallop, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_BayScallop)
summary(linearMod_1997)
both_nonsig(CommLandings_BayScallop, CommLandings_BayScallop$pounds, intercept_CommLandings_BayScallop, pdata_CommLandings_BayScallop, mod.dsig_CommLandings_BayScallop, "Lbs Landed", "Year", "Commercial Landings for Bay Scallop") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_BayScallopGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Blue crab
p2mod_CommLandings_BlueCrab <- GAM_predict_p2mod(CommLandings_BlueCrab, mod_CommLandings_BlueCrab)
intercept_CommLandings_BlueCrab = as.numeric(attr(p2mod_CommLandings_BlueCrab,"constant")) 
pdata_CommLandings_BlueCrab <- GAM_predict_pdata(CommLandings_BlueCrab, mod_CommLandings_BlueCrab)
mod.dsig_CommLandings_BlueCrab <- GAM_deriv(pdata_CommLandings_BlueCrab, mod_CommLandings_BlueCrab)
linearMod <- lm(pounds ~ year, data= CommLandings_BlueCrab)
summary(linearMod)
dfpost1997_CommLandings_BlueCrab <- filter(CommLandings_BlueCrab, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_BlueCrab)
summary(linearMod_1997)
both_sig(CommLandings_BlueCrab, CommLandings_BlueCrab$pounds, intercept_CommLandings_BlueCrab, pdata_CommLandings_BlueCrab, mod.dsig_CommLandings_BlueCrab, dfpost1997_CommLandings_BlueCrab, dfpost1997_CommLandings_BlueCrab$pounds, "Lbs Landed", "Year", "Commercial Landings for Blue Crab") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_BlueCrabGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Hard Clams
p2mod_CommLandings_HardClams <- GAM_predict_p2mod(CommLandings_HardClams, mod_CommLandings_HardClams)
intercept_CommLandings_HardClams = as.numeric(attr(p2mod_CommLandings_HardClams,"constant")) 
pdata_CommLandings_HardClams <- GAM_predict_pdata(CommLandings_HardClams, mod_CommLandings_HardClams)
mod.dsig_CommLandings_HardClams <- GAM_deriv(pdata_CommLandings_HardClams, mod_CommLandings_HardClams)
linearMod <- lm(pounds ~ year, data= CommLandings_HardClams)
summary(linearMod)
dfpost1997_CommLandings_HardClams <- filter(CommLandings_HardClams, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_HardClams)
summary(linearMod_1997)
both_sig(CommLandings_HardClams, CommLandings_HardClams$pounds, intercept_CommLandings_HardClams, pdata_CommLandings_HardClams, mod.dsig_CommLandings_HardClams, dfpost1997_CommLandings_HardClams, dfpost1997_CommLandings_HardClams$pounds, "Lbs Landed", "Year", "Commercial Landings for Hard Clams") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_HardClamsGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Kingfishes
p2mod_CommLandings_Kingfishes <- GAM_predict_p2mod(CommLandings_Kingfishes, mod_CommLandings_Kingfishes)
intercept_CommLandings_Kingfishes = as.numeric(attr(p2mod_CommLandings_Kingfishes,"constant")) 
pdata_CommLandings_Kingfishes <- GAM_predict_pdata(CommLandings_Kingfishes, mod_CommLandings_Kingfishes)
mod.dsig_CommLandings_Kingfishes <- GAM_deriv(pdata_CommLandings_Kingfishes, mod_CommLandings_Kingfishes)
linearMod <- lm(pounds ~ year, data= CommLandings_Kingfishes)
summary(linearMod)
dfpost1997_CommLandings_Kingfishes <- filter(CommLandings_Kingfishes, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_Kingfishes)
summary(linearMod_1997)
short_sig(CommLandings_Kingfishes, CommLandings_Kingfishes$pounds, intercept_CommLandings_Kingfishes, pdata_CommLandings_Kingfishes, mod.dsig_CommLandings_Kingfishes, dfpost1997_CommLandings_Kingfishes, dfpost1997_CommLandings_Kingfishes$pounds, "Lbs Lnaded", "Year", "Commercial Landings for Kingfishes") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_KingfishesGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Oysters
p2mod_CommLandings_Oysters <- GAM_predict_p2mod(CommLandings_Oysters, mod_CommLandings_Oysters)
intercept_CommLandings_Oysters = as.numeric(attr(p2mod_CommLandings_Oysters,"constant")) 
pdata_CommLandings_Oysters <- GAM_predict_pdata(CommLandings_Oysters, mod_CommLandings_Oysters)
mod.dsig_CommLandings_Oysters <- GAM_deriv(pdata_CommLandings_Oysters, mod_CommLandings_Oysters)
linearMod <- lm(pounds ~ year, data= CommLandings_Oysters)
summary(linearMod)
dfpost1997_CommLandings_Oysters <- filter(CommLandings_Oysters, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_Oysters)
summary(linearMod_1997)
both_sig(CommLandings_Oysters, CommLandings_Oysters$pounds, intercept_CommLandings_Oysters, pdata_CommLandings_Oysters, mod.dsig_CommLandings_Oysters, dfpost1997_CommLandings_Oysters, dfpost1997_CommLandings_Oysters$pounds, "Lbs Lnaded", "Year", "Commercial Landings for Oysters") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_OystersGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Red Drum
p2mod_CommLandings_RedDrum <- GAM_predict_p2mod(CommLandings_RedDrum, mod_CommLandings_RedDrum)
intercept_CommLandings_RedDrum = as.numeric(attr(p2mod_CommLandings_RedDrum,"constant")) 
pdata_CommLandings_RedDrum <- GAM_predict_pdata(CommLandings_RedDrum, mod_CommLandings_RedDrum)
mod.dsig_CommLandings_RedDrum <- GAM_deriv(pdata_CommLandings_RedDrum, mod_CommLandings_RedDrum)
linearMod <- lm(pounds ~ year, data= CommLandings_RedDrum)
summary(linearMod)
dfpost1997_CommLandings_RedDrum <- filter(CommLandings_RedDrum, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_RedDrum)
summary(linearMod_1997)
both_nonsig(CommLandings_RedDrum, CommLandings_RedDrum$pounds, intercept_CommLandings_RedDrum, pdata_CommLandings_RedDrum, mod.dsig_CommLandings_RedDrum, "Lbs Lnaded", "Year", "Commercial Landings for Red Drum") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_RedDrumGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##River Herring 
p2mod_CommLandings_RiverHerring <- GAM_predict_p2mod(CommLandings_RiverHerring, mod_CommLandings_RiverHerring)
intercept_CommLandings_RiverHerring = as.numeric(attr(p2mod_CommLandings_RiverHerring,"constant")) 
pdata_CommLandings_RiverHerring <- GAM_predict_pdata(CommLandings_RiverHerring, mod_CommLandings_RiverHerring)
mod.dsig_CommLandings_RiverHerring <- GAM_deriv(pdata_CommLandings_RiverHerring, mod_CommLandings_RiverHerring)
linearMod <- lm(pounds ~ year, data= CommLandings_RiverHerring)
summary(linearMod)
dfpost1997_CommLandings_RiverHerring <- filter(CommLandings_RiverHerring, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_RiverHerring)
summary(linearMod_1997)
both_sig(CommLandings_RiverHerring, CommLandings_RiverHerring$pounds, intercept_CommLandings_RiverHerring, pdata_CommLandings_RiverHerring, mod.dsig_CommLandings_RiverHerring, dfpost1997_CommLandings_RiverHerring, dfpost1997_CommLandings_RiverHerring$pounds, "Lbs Lnaded", "Year", "Commercial Landings for River Herring") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_RiverHerringGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Southern Flounder
p2mod_CommLandings_SouthernFlounder <- GAM_predict_p2mod(CommLandings_SouthernFlounder, mod_CommLandings_SouthernFlounder)
intercept_CommLandings_SouthernFlounder = as.numeric(attr(p2mod_CommLandings_SouthernFlounder,"constant")) 
pdata_CommLandings_SouthernFlounder <- GAM_predict_pdata(CommLandings_SouthernFlounder, mod_CommLandings_SouthernFlounder)
mod.dsig_CommLandings_SouthernFlounder <- GAM_deriv(pdata_CommLandings_SouthernFlounder, mod_CommLandings_SouthernFlounder)
linearMod <- lm(pounds ~ year, data= CommLandings_SouthernFlounder)
summary(linearMod)
dfpost1997_CommLandings_SouthernFlounder <- filter(CommLandings_SouthernFlounder, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_SouthernFlounder)
summary(linearMod_1997)
both_sig(CommLandings_SouthernFlounder, CommLandings_SouthernFlounder$pounds, intercept_CommLandings_SouthernFlounder, pdata_CommLandings_SouthernFlounder, mod.dsig_CommLandings_SouthernFlounder, dfpost1997_CommLandings_SouthernFlounder, dfpost1997_CommLandings_SouthernFlounder$pounds, "Lbs Lnaded", "Year", "Commercial Landings for Southern Flounder") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_SouthernFlounderGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Spotted Seatrout 
p2mod_CommLandings_SpottedSeatrout <- GAM_predict_p2mod(CommLandings_SpottedSeatrout, mod_CommLandings_SpottedSeatrout)
intercept_CommLandings_SpottedSeatrout = as.numeric(attr(p2mod_CommLandings_SpottedSeatrout,"constant")) 
pdata_CommLandings_SpottedSeatrout <- GAM_predict_pdata(CommLandings_SpottedSeatrout, mod_CommLandings_SpottedSeatrout)
mod.dsig_CommLandings_SpottedSeatrout <- GAM_deriv(pdata_CommLandings_SpottedSeatrout, mod_CommLandings_SpottedSeatrout)
linearMod <- lm(pounds ~ year, data= CommLandings_SpottedSeatrout)
summary(linearMod)
dfpost1997_CommLandings_SpottedSeatrout <- filter(CommLandings_SpottedSeatrout, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_SpottedSeatrout)
summary(linearMod_1997)
both_nonsig(CommLandings_SpottedSeatrout, CommLandings_SpottedSeatrout$pounds, intercept_CommLandings_SpottedSeatrout, pdata_CommLandings_SpottedSeatrout, mod.dsig_CommLandings_SpottedSeatrout, "Lbs Lnaded", "Year", "Commercial Landings for Spotted Seatrout") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_SpottedSeatroutGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Striped Bass 
p2mod_CommLandings_StripedBass <- GAM_predict_p2mod(CommLandings_StripedBass, mod_CommLandings_StripedBass)
intercept_CommLandings_StripedBass = as.numeric(attr(p2mod_CommLandings_StripedBass,"constant")) 
pdata_CommLandings_StripedBass <- GAM_predict_pdata(CommLandings_StripedBass, mod_CommLandings_StripedBass)
mod.dsig_CommLandings_StripedBass <- GAM_deriv(pdata_CommLandings_StripedBass, mod_CommLandings_StripedBass)
linearMod <- lm(pounds ~ year, data= CommLandings_StripedBass)
summary(linearMod)
dfpost1997_CommLandings_StripedBass <- filter(CommLandings_StripedBass, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_StripedBass)
summary(linearMod_1997)
both_sig(CommLandings_StripedBass, CommLandings_StripedBass$pounds, intercept_CommLandings_StripedBass, pdata_CommLandings_StripedBass, mod.dsig_CommLandings_StripedBass, dfpost1997_CommLandings_StripedBass, dfpost1997_CommLandings_StripedBass$pounds, "Lbs Lnaded", "Year", "Commercial Landings for Striped Bass") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_StripedBassGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')
CommLandings_StripedBass  <- CommLandings %>% filter(species %in% "Striped Bass")
k_det(CommLandings_StripedBass)
gam_diagn(CommLandings_StripedBass$pounds, 6, CommLandings_StripedBass) 
mod_CommLandings_StripedBass <- gam(pounds ~ s(year, k=  6), data = CommLandings_StripedBass)

##Striped Mullet
p2mod_CommLandings_StripedMullet <- GAM_predict_p2mod(CommLandings_StripedMullet, mod_CommLandings_StripedMullet)
intercept_CommLandings_StripedMullet = as.numeric(attr(p2mod_CommLandings_StripedMullet,"constant")) 
pdata_CommLandings_StripedMullet <- GAM_predict_pdata(CommLandings_StripedMullet, mod_CommLandings_StripedMullet)
mod.dsig_CommLandings_StripedMullet <- GAM_deriv(pdata_CommLandings_StripedMullet, mod_CommLandings_StripedMullet)
linearMod <- lm(pounds ~ year, data= CommLandings_StripedMullet)
summary(linearMod)
dfpost1997_CommLandings_StripedMullet <- filter(CommLandings_StripedMullet, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_StripedMullet)
summary(linearMod_1997)
both_sig(CommLandings_StripedMullet, CommLandings_StripedMullet$pounds, intercept_CommLandings_StripedMullet, pdata_CommLandings_StripedMullet, mod.dsig_CommLandings_StripedMullet, dfpost1997_CommLandings_StripedMullet, dfpost1997_CommLandings_StripedMullet$pounds, "Lbs Lnaded", "Year", "Commercial Landings for Striped Mullet") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_StripedMulletGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Brown Shrimp
p2mod_CommLandings_BrownShrimp <- GAM_predict_p2mod(CommLandings_BrownShrimp, mod_CommLandings_BrownShrimp)
intercept_CommLandings_BrownShrimp = as.numeric(attr(p2mod_CommLandings_BrownShrimp,"constant")) 
pdata_CommLandings_BrownShrimp <- GAM_predict_pdata(CommLandings_BrownShrimp, mod_CommLandings_BrownShrimp)
mod.dsig_CommLandings_BrownShrimp <- GAM_deriv(pdata_CommLandings_BrownShrimp, mod_CommLandings_BrownShrimp)
linearMod <- lm(pounds ~ year, data= CommLandings_BrownShrimp)
summary(linearMod)
dfpost1997_CommLandings_BrownShrimp <- filter(CommLandings_BrownShrimp, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_BrownShrimp)
summary(linearMod_1997)
both_nonsig(CommLandings_BrownShrimp, CommLandings_BrownShrimp$pounds, intercept_CommLandings_BrownShrimp, pdata_CommLandings_BrownShrimp, mod.dsig_CommLandings_BrownShrimp, "Lbs Lnaded", "Year", "Commercial Landings for Brown Shrimp") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_BrownShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Pink Shrimp
p2mod_CommLandings_PinkShrimp <- GAM_predict_p2mod(CommLandings_PinkShrimp, mod_CommLandings_PinkShrimp)
intercept_CommLandings_PinkShrimp = as.numeric(attr(p2mod_CommLandings_PinkShrimp,"constant")) 
pdata_CommLandings_PinkShrimp <- GAM_predict_pdata(CommLandings_PinkShrimp, mod_CommLandings_PinkShrimp)
mod.dsig_CommLandings_PinkShrimp <- GAM_deriv(pdata_CommLandings_PinkShrimp, mod_CommLandings_PinkShrimp)
linearMod <- lm(pounds ~ year, data= CommLandings_PinkShrimp)
summary(linearMod)
dfpost1997_CommLandings_PinkShrimp <- filter(CommLandings_PinkShrimp, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_PinkShrimp)
summary(linearMod_1997)
both_nonsig(CommLandings_PinkShrimp, CommLandings_PinkShrimp$pounds, intercept_CommLandings_PinkShrimp, pdata_CommLandings_PinkShrimp, mod.dsig_CommLandings_PinkShrimp, "Lbs Lnaded", "Year", "Commercial Landings for Pink Shrimp") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_PinkShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##White Shrimp
p2mod_CommLandings_WhiteShrimp <- GAM_predict_p2mod(CommLandings_WhiteShrimp, mod_CommLandings_WhiteShrimp)
intercept_CommLandings_WhiteShrimp = as.numeric(attr(p2mod_CommLandings_WhiteShrimp,"constant")) 
pdata_CommLandings_WhiteShrimp <- GAM_predict_pdata(CommLandings_WhiteShrimp, mod_CommLandings_WhiteShrimp)
mod.dsig_CommLandings_WhiteShrimp <- GAM_deriv(pdata_CommLandings_WhiteShrimp, mod_CommLandings_WhiteShrimp)
linearMod <- lm(pounds ~ year, data= CommLandings_WhiteShrimp)
summary(linearMod)
dfpost1997_CommLandings_WhiteShrimp <- filter(CommLandings_WhiteShrimp, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_CommLandings_WhiteShrimp)
summary(linearMod_1997)
both_sig(CommLandings_WhiteShrimp, CommLandings_WhiteShrimp$pounds, intercept_CommLandings_WhiteShrimp, pdata_CommLandings_WhiteShrimp, mod.dsig_CommLandings_WhiteShrimp, dfpost1997_CommLandings_WhiteShrimp, dfpost1997_CommLandings_WhiteShrimp$pounds, "Lbs Lnaded", "Year", "Commercial Landings for White Shrimp") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_WhiteShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Birds
p2mod_BirdNests <- GAM_predict_p2mod(BirdNests, mod_BirdNests)
intercept_BirdNests = as.numeric(attr(p2mod_BirdNests,"constant")) 
pdata_BirdNests <- GAM_predict_pdata(BirdNests, mod_BirdNests)
mod.dsig_BirdNests <- GAM_deriv(pdata_BirdNests, mod_BirdNests)
linearMod <- lm(sum_nests ~ year, data= BirdNests)
summary(linearMod)
dfpost1997_BirdNests <- filter(BirdNests, year > 1997)
linearMod_1997 <- lm(sum_nests ~ year, data=dfpost1997_BirdNests)
summary(linearMod_1997)
both_nonsig(BirdNests, BirdNests$sum_nests, intercept_BirdNests, pdata_BirdNests, mod.dsig_BirdNests, "Number of Nests", "Year", "Number of Colonial Waterbird Nests\n in Coastal NC") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_BirdNestsGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Commercial participants

##Bay scallop
p2mod_CommParts_BayScallop <- GAM_predict_p2mod(CommParts_BayScallop, mod_CommParts_BayScallop)
intercept_CommParts_BayScallop = as.numeric(attr(p2mod_CommParts_BayScallop,"constant")) 
pdata_CommParts_BayScallop <- GAM_predict_pdata(CommParts_BayScallop, mod_CommParts_BayScallop)
mod.dsig_CommParts_BayScallop <- GAM_deriv(pdata_CommParts_BayScallop, mod_CommParts_BayScallop)
linearMod <- lm(participants ~ year, data= CommParts_BayScallop)
summary(linearMod)
dfpost1997_CommParts_BayScallop <- filter(CommParts_BayScallop, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_BayScallop)
summary(linearMod_1997)
long_sig(CommParts_BayScallop, CommParts_BayScallop$participants, intercept_CommParts_BayScallop, pdata_CommParts_BayScallop, mod.dsig_CommParts_BayScallop, "Number of Participants", "Year", "Number of Participants in \n Bay Scallop Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_BayScallopGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Blue Crab
p2mod_CommParts_BlueCrab <- GAM_predict_p2mod(CommParts_BlueCrab, mod_CommParts_BlueCrab)
intercept_CommParts_BlueCrab = as.numeric(attr(p2mod_CommParts_BlueCrab,"constant")) 
pdata_CommParts_BlueCrab <- GAM_predict_pdata(CommParts_BlueCrab, mod_CommParts_BlueCrab)
mod.dsig_CommParts_BlueCrab <- GAM_deriv(pdata_CommParts_BlueCrab, mod_CommParts_BlueCrab)
linearMod <- lm(participants ~ year, data= CommParts_BlueCrab)
summary(linearMod)
dfpost1997_CommParts_BlueCrab <- filter(CommParts_BlueCrab, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_BlueCrab)
summary(linearMod_1997)
both_sig(CommParts_BlueCrab, CommParts_BlueCrab$participants, intercept_CommParts_BlueCrab, pdata_CommParts_BlueCrab, mod.dsig_CommParts_BlueCrab, dfpost1997_CommParts_BlueCrab, dfpost1997_CommParts_BlueCrab$participants, "Number of Participants", "Year", "Number of Participants in \n Blue Crab Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_BlueCrabGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Hard Clams
p2mod_CommParts_HardClams <- GAM_predict_p2mod(CommParts_HardClams, mod_CommParts_HardClams)
intercept_CommParts_HardClams = as.numeric(attr(p2mod_CommParts_HardClams,"constant")) 
pdata_CommParts_HardClams <- GAM_predict_pdata(CommParts_HardClams, mod_CommParts_HardClams)
mod.dsig_CommParts_HardClams <- GAM_deriv(pdata_CommParts_HardClams, mod_CommParts_HardClams)
linearMod <- lm(participants ~ year, data= CommParts_HardClams)
summary(linearMod)
dfpost1997_CommParts_HardClams <- filter(CommParts_HardClams, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_HardClams)
summary(linearMod_1997)
both_sig(CommParts_HardClams, CommParts_HardClams$participants, intercept_CommParts_HardClams, pdata_CommParts_HardClams, mod.dsig_CommParts_HardClams, dfpost1997_CommParts_HardClams, dfpost1997_CommParts_HardClams$participants, "Number of Participants", "Year", "Number of Participants in \n Hard Clam Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_HardClamsGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Kingfishes
p2mod_CommParts_Kingfishes <- GAM_predict_p2mod(CommParts_Kingfishes, mod_CommParts_Kingfishes)
intercept_CommParts_Kingfishes = as.numeric(attr(p2mod_CommParts_Kingfishes,"constant")) 
pdata_CommParts_Kingfishes <- GAM_predict_pdata(CommParts_Kingfishes, mod_CommParts_Kingfishes)
mod.dsig_CommParts_Kingfishes <- GAM_deriv(pdata_CommParts_Kingfishes, mod_CommParts_Kingfishes)
linearMod <- lm(participants ~ year, data= CommParts_Kingfishes)
summary(linearMod)
dfpost1997_CommParts_Kingfishes <- filter(CommParts_Kingfishes, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_Kingfishes)
summary(linearMod_1997)
both_sig(CommParts_Kingfishes, CommParts_Kingfishes$participants, intercept_CommParts_Kingfishes, pdata_CommParts_Kingfishes, mod.dsig_CommParts_Kingfishes, dfpost1997_CommParts_Kingfishes, dfpost1997_CommParts_Kingfishes$participants, "Number of Participants", "Year", "Number of Participants in \n Kingfish Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_KingfishesGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Oyster
p2mod_CommParts_Oyster <- GAM_predict_p2mod(CommParts_Oyster, mod_CommParts_Oyster)
intercept_CommParts_Oyster = as.numeric(attr(p2mod_CommParts_Oyster,"constant")) 
pdata_CommParts_Oyster <- GAM_predict_pdata(CommParts_Oyster, mod_CommParts_Oyster)
mod.dsig_CommParts_Oyster <- GAM_deriv(pdata_CommParts_Oyster, mod_CommParts_Oyster)
linearMod <- lm(participants ~ year, data= CommParts_Oyster)
summary(linearMod)
dfpost1997_CommParts_Oyster <- filter(CommParts_Oyster, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_Oyster)
summary(linearMod_1997)
both_sig(CommParts_Oyster, CommParts_Oyster$participants, intercept_CommParts_Oyster, pdata_CommParts_Oyster, mod.dsig_CommParts_Oyster, dfpost1997_CommParts_Oyster, dfpost1997_CommParts_Oyster$participants, "Number of Participants", "Year", "Number of Participants in \n Oyster Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_OysterGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Red Drum 
p2mod_CommParts_RedDrum <- GAM_predict_p2mod(CommLandings_RedDrum, mod_CommParts_RedDrum)
intercept_CommParts_RedDrum = as.numeric(attr(p2mod_CommParts_RedDrum,"constant")) 
pdata_CommParts_RedDrum <- GAM_predict_pdata(CommParts_RedDrum, mod_CommParts_RedDrum)
mod.dsig_CommParts_RedDrum <- GAM_deriv(pdata_CommParts_RedDrum, mod_CommParts_RedDrum)
linearMod <- lm(participants ~ year, data= CommParts_RedDrum)
summary(linearMod)
dfpost1997_CommParts_RedDrum <- filter(CommParts_RedDrum, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_RedDrum)
summary(linearMod_1997)
both_sig(CommParts_RedDrum, CommParts_RedDrum$participants, intercept_CommParts_RedDrum, pdata_CommParts_RedDrum, mod.dsig_CommParts_RedDrum, dfpost1997_CommParts_RedDrum, dfpost1997_CommParts_RedDrum$participants, "Number of Participants", "Year", "Number of Participants in \n Red Drum Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_ReDrumGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##River Herring
p2mod_CommParts_RiverHerring <- GAM_predict_p2mod(CommParts_RiverHerring, mod_CommParts_RiverHerring)
intercept_CommParts_RiverHerring = as.numeric(attr(p2mod_CommParts_RiverHerring,"constant")) 
pdata_CommParts_RiverHerring <- GAM_predict_pdata(CommParts_RiverHerring, mod_CommParts_RiverHerring)
mod.dsig_CommParts_RiverHerring <- GAM_deriv(pdata_CommParts_RiverHerring, mod_CommParts_RiverHerring)
linearMod <- lm(participants ~ year, data= CommParts_RiverHerring)
summary(linearMod)
dfpost1997_CommParts_RiverHerring <- filter(CommParts_RiverHerring, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_RiverHerring)
summary(linearMod_1997)
both_sig(CommParts_RiverHerring, CommParts_RiverHerring$participants, intercept_CommParts_RiverHerring, pdata_CommParts_RiverHerring, mod.dsig_CommParts_RiverHerring, dfpost1997_CommParts_RiverHerring, dfpost1997_CommParts_RiverHerring$participants, "Number of Participants", "Year", "Number of Participants in \n River Herring Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_RiverHerringGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Southern Flounder
p2mod_CommParts_SouthernFlounder <- GAM_predict_p2mod(CommParts_SouthernFlounder, mod_CommParts_SouthernFlounder)
intercept_CommParts_SouthernFlounder = as.numeric(attr(p2mod_CommParts_SouthernFlounder,"constant")) 
pdata_CommParts_SouthernFlounder <- GAM_predict_pdata(CommParts_SouthernFlounder, mod_CommParts_SouthernFlounder)
mod.dsig_CommParts_SouthernFlounder <- GAM_deriv(pdata_CommParts_SouthernFlounder, mod_CommParts_SouthernFlounder)
linearMod <- lm(participants ~ year, data= CommParts_SouthernFlounder)
summary(linearMod)
dfpost1997_CommParts_SouthernFlounder <- filter(CommParts_SouthernFlounder, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_SouthernFlounder)
summary(linearMod_1997)
both_sig(CommParts_SouthernFlounder, CommParts_SouthernFlounder$participants, intercept_CommParts_SouthernFlounder, pdata_CommParts_SouthernFlounder, mod.dsig_CommParts_SouthernFlounder, dfpost1997_CommParts_SouthernFlounder, dfpost1997_CommParts_SouthernFlounder$participants, "Number of Participants", "Year", "Number of Participants in \n Southern Flounder Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_SouthernFlounderGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Striped Bass
p2mod_CommParts_StripedBass <- GAM_predict_p2mod(CommParts_StripedBass, mod_CommParts_StripedBass)
intercept_CommParts_StripedBass = as.numeric(attr(p2mod_CommParts_StripedBass,"constant")) 
pdata_CommParts_StripedBass <- GAM_predict_pdata(CommParts_StripedBass, mod_CommParts_StripedBass)
mod.dsig_CommParts_StripedBass <- GAM_deriv(pdata_CommParts_StripedBass, mod_CommParts_StripedBass)
linearMod <- lm(participants ~ year, data= CommParts_StripedBass)
summary(linearMod)
dfpost1997_CommParts_StripedBass <- filter(CommParts_StripedBass, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_StripedBass)
summary(linearMod_1997)
both_sig(CommParts_StripedBass, CommParts_StripedBass$participants, intercept_CommParts_StripedBass, pdata_CommParts_StripedBass, mod.dsig_CommParts_StripedBass, dfpost1997_CommParts_StripedBass, dfpost1997_CommParts_StripedBass$participants, "Number of Participants", "Year", "Number of Participants in \n Striped Bass Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_StripedBassGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Striped Mullet 
p2mod_CommParts_StripedMullet <- GAM_predict_p2mod(CommParts_StripedMullet, mod_CommParts_StripedMullet)
intercept_CommParts_StripedMullet = as.numeric(attr(p2mod_CommParts_StripedMullet,"constant")) 
pdata_CommParts_StripedMullet <- GAM_predict_pdata(CommParts_StripedMullet, mod_CommParts_StripedMullet)
mod.dsig_CommParts_StripedMullet <- GAM_deriv(pdata_CommParts_StripedMullet, mod_CommParts_StripedMullet)
linearMod <- lm(participants ~ year, data= CommParts_StripedMullet)
summary(linearMod)
dfpost1997_CommParts_StripedMullet <- filter(CommParts_StripedMullet, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_StripedMullet)
summary(linearMod_1997)
both_sig(CommParts_StripedMullet, CommParts_StripedMullet$participants, intercept_CommParts_StripedMullet, pdata_CommParts_StripedMullet, mod.dsig_CommParts_StripedMullet, dfpost1997_CommParts_StripedMullet, dfpost1997_CommParts_StripedMullet$participants, "Number of Participants", "Year", "Number of Participants in \n Striped Mullet Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_StripedMulletGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Spotted Seatrout
p2mod_CommParts_SpottedSeatrout <- GAM_predict_p2mod(CommParts_SpottedSeatrout, mod_CommParts_SpottedSeatrout)
intercept_CommParts_SpottedSeatrout = as.numeric(attr(p2mod_CommParts_SpottedSeatrout,"constant")) 
pdata_CommParts_SpottedSeatrout <- GAM_predict_pdata(CommParts_SpottedSeatrout, mod_CommParts_SpottedSeatrout)
mod.dsig_CommParts_SpottedSeatrout <- GAM_deriv(pdata_CommParts_SpottedSeatrout, mod_CommParts_SpottedSeatrout)
linearMod <- lm(participants ~ year, data= CommParts_SpottedSeatrout)
summary(linearMod)
dfpost1997_CommParts_SpottedSeatrout <- filter(CommParts_SpottedSeatrout, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_SpottedSeatrout)
summary(linearMod_1997)
both_sig(CommParts_SpottedSeatrout, CommParts_SpottedSeatrout$participants, intercept_CommParts_SpottedSeatrout, pdata_CommParts_SpottedSeatrout, mod.dsig_CommParts_SpottedSeatrout, dfpost1997_CommParts_SpottedSeatrout, dfpost1997_CommParts_SpottedSeatrout$participants, "Number of Participants", "Year", "Number of Participants in \n Spotted Seatrout Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/", "CommLandings_CommParts_SpottedSeatroutGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Brown Shrimp
p2mod_CommParts_BrownShrimp <- GAM_predict_p2mod(CommParts_BrownShrimp, mod_CommParts_BrownShrimp)
intercept_CommParts_BrownShrimp = as.numeric(attr(p2mod_CommParts_BrownShrimp,"constant")) 
pdata_CommParts_BrownShrimp <- GAM_predict_pdata(CommParts_BrownShrimp, mod_CommParts_BrownShrimp)
mod.dsig_CommParts_BrownShrimp <- GAM_deriv(pdata_CommParts_BrownShrimp, mod_CommParts_BrownShrimp)
linearMod <- lm(participants ~ year, data= CommParts_BrownShrimp)
summary(linearMod)
dfpost1997_CommParts_BrownShrimp <- filter(CommParts_BrownShrimp, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_BrownShrimp)
summary(linearMod_1997)
both_sig(CommParts_BrownShrimp, CommParts_BrownShrimp$participants, intercept_CommParts_BrownShrimp, pdata_CommParts_BrownShrimp, mod.dsig_CommParts_BrownShrimp, dfpost1997_CommParts_BrownShrimp, dfpost1997_CommParts_BrownShrimp$participants, "Number of Participants", "Year", "Number of Participants in \n Brown Shrimp Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_BrownShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Pink Shrimp
p2mod_CommParts_PinkShrimp <- GAM_predict_p2mod(CommParts_PinkShrimp, mod_CommParts_PinkShrimp)
intercept_CommParts_PinkShrimp = as.numeric(attr(p2mod_CommParts_PinkShrimp,"constant")) 
pdata_CommParts_PinkShrimp <- GAM_predict_pdata(CommParts_PinkShrimp, mod_CommParts_PinkShrimp)
mod.dsig_CommParts_PinkShrimp <- GAM_deriv(pdata_CommParts_PinkShrimp, mod_CommParts_PinkShrimp)
linearMod <- lm(participants ~ year, data= CommParts_PinkShrimp)
summary(linearMod)
dfpost1997_CommParts_PinkShrimp <- filter(CommParts_PinkShrimp, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_PinkShrimp)
summary(linearMod_1997)
both_sig(CommParts_PinkShrimp, CommParts_PinkShrimp$participants, intercept_CommParts_PinkShrimp, pdata_CommParts_PinkShrimp, mod.dsig_CommParts_PinkShrimp, dfpost1997_CommParts_PinkShrimp, dfpost1997_CommParts_PinkShrimp$participants, "Number of Participants", "Year", "Number of Participants in \n Pink Shrimp Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_PinkShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##White Shrimp
p2mod_CommParts_WhiteShrimp <- GAM_predict_p2mod(CommParts_WhiteShrimp, mod_CommParts_WhiteShrimp)
intercept_CommParts_WhiteShrimp = as.numeric(attr(p2mod_CommParts_WhiteShrimp,"constant")) 
pdata_CommParts_WhiteShrimp <- GAM_predict_pdata(CommParts_WhiteShrimp, mod_CommParts_WhiteShrimp)
mod.dsig_CommParts_WhiteShrimp <- GAM_deriv(pdata_CommParts_WhiteShrimp, mod_CommParts_WhiteShrimp)
linearMod <- lm(participants ~ year, data= CommParts_WhiteShrimp)
summary(linearMod)
dfpost1997_CommParts_WhiteShrimp <- filter(CommParts_WhiteShrimp, year > 1997)
linearMod_1997 <- lm(participants ~ year, data=dfpost1997_CommParts_WhiteShrimp)
summary(linearMod_1997)
both_sig(CommParts_WhiteShrimp, CommParts_WhiteShrimp$participants, intercept_CommParts_WhiteShrimp, pdata_CommParts_WhiteShrimp, mod.dsig_CommParts_WhiteShrimp, dfpost1997_CommParts_WhiteShrimp, dfpost1997_CommParts_WhiteShrimp$participants, "Number of Participants", "Year", "Number of Participants in \n White Shrimp Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "CommLandings_CommParts_WhiteShrimpGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Rec Catch
p2mod_RecCatch <- GAM_predict_p2mod(RecCatch, mod_RecCatch)
intercept_RecCatch = as.numeric(attr(p2mod_RecCatch,"constant")) 
pdata_RecCatch <- GAM_predict_pdata(RecCatch, mod_RecCatch)
mod.dsig_RecCatch <- GAM_deriv(pdata_RecCatch, mod_RecCatch)
linearMod <- lm(sum_catch ~ year, data= RecCatch)
summary(linearMod)
dfpost1997_RecCatch <- filter(RecCatch, year > 1997)
linearMod_1997 <- lm(sum_catch ~ year, data=dfpost1997_RecCatch)
summary(linearMod_1997)
both_sig(RecCatch, RecCatch$sum_catch, intercept_RecCatch, pdata_RecCatch, mod.dsig_RecCatch, dfpost1997_RecCatch, dfpost1997_RecCatch$sum_catch, "Number of Fish", "Year", "Total Recreational Catch") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "RecCatchAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Rec Rel Alive
p2mod_RecRelAlive <- GAM_predict_p2mod(RecRelAlive, mod_RecRelAlive)
intercept_RecRelAlive = as.numeric(attr(p2mod_RecRelAlive,"constant")) 
pdata_RecRelAlive <- GAM_predict_pdata(RecRelAlive, mod_RecRelAlive)
mod.dsig_RecRelAlive <- GAM_deriv(pdata_RecRelAlive, mod_RecRelAlive)
linearMod <- lm(relalive ~ year, data= RecRelAlive)
summary(linearMod)
dfpost1997_RecRelAlive <- filter(RecRelAlive, year > 1997)
linearMod_1997 <- lm(relalive ~ year, data=dfpost1997_RecRelAlive)
summary(linearMod_1997)
both_sig(RecRelAlive, RecRelAlive$relalive, intercept_RecRelAlive, pdata_RecRelAlive, mod.dsig_RecRelAlive, dfpost1997_RecRelAlive, dfpost1997_RecRelAlive$relalive, "Number of Fish Released Alive", "Year", "Total Recreational Fishes Released Alive") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "RecRelAliveAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Rec Rel Alive reduced
p2mod_RecRelAliveRed <- GAM_predict_p2mod(RecRelAliveRed, mod_RecRelAliveRed)
intercept_RecRelAliveRed = as.numeric(attr(p2mod_RecRelAliveRed,"constant")) 
pdata_RecRelAliveRed <- GAM_predict_pdata(RecRelAliveRed, mod_RecRelAliveRed)
mod.dsig_RecRelAliveRed <- GAM_deriv(pdata_RecRelAliveRed, mod_RecRelAliveRed)
linearMod <- lm(relalive ~ year, data= RecRelAliveRed)
summary(linearMod)
dfpost1997_RecRelAliveRed <- filter(RecRelAliveRed, year > 1997)
linearMod_1997 <- lm(relalive ~ year, data=dfpost1997_RecRelAliveRed)
summary(linearMod_1997)
short_sig(RecRelAliveRed, RecRelAliveRed$relalive, intercept_RecRelAliveRed, pdata_RecRelAliveRed, mod.dsig_RecRelAliveRed, dfpost1997_RecRelAliveRed, dfpost1997_RecRelAliveRed$relalive, "Number of Fish Released Alive", "Year", "Total Recreational Fishes Released Alive") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "RecRelAliveRedAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Menhaden fishery: 

###Menhaden Bait: 
p2mod_MenhadenBait <- GAM_predict_p2mod(MenhadenBait, mod_MenhadenBait)
intercept_MenhadenBait = as.numeric(attr(p2mod_MenhadenBait,"constant")) 
pdata_MenhadenBait <- GAM_predict_pdata(MenhadenBait, mod_MenhadenBait)
mod.dsig_MenhadenBait <- GAM_deriv(pdata_MenhadenBait, mod_MenhadenBait)
linearMod <- lm(pounds ~ year, data= MenhadenBait)
summary(linearMod)
dfpost1997_MenhadenBait <- filter(MenhadenBait, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_MenhadenBait)
summary(linearMod_1997)
both_sig(MenhadenBait, MenhadenBait$pounds, intercept_MenhadenBait, pdata_MenhadenBait, mod.dsig_MenhadenBait, dfpost1997_MenhadenBait, dfpost1997_MenhadenBait$pounds, "Pounds", "Year", "Total Landings in Menhaden \n Bait Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "MenhadenBaitGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

###Menhaden Reduction: 
p2mod_MenhadenReduction <- GAM_predict_p2mod(MenhadenReduction, mod_MenhadenReduction)
intercept_MenhadenReduction = as.numeric(attr(p2mod_MenhadenReduction,"constant")) 
pdata_MenhadenReduction <- GAM_predict_pdata(MenhadenReduction, mod_MenhadenReduction)
mod.dsig_MenhadenReduction <- GAM_deriv(pdata_MenhadenReduction, mod_MenhadenReduction)
linearMod <- lm(pounds ~ year, data= MenhadenReduction)
summary(linearMod)
dfpost1997_MenhadenReduction <- filter(MenhadenReduction, year > 1997)
linearMod_1997 <- lm(pounds ~ year, data=dfpost1997_MenhadenReduction)
summary(linearMod_1997)
long_sig(MenhadenReduction, MenhadenReduction$pounds, intercept_MenhadenReduction, pdata_MenhadenReduction, mod.dsig_MenhadenReduction, "Pounds", "Year", "Total Landings in Menhaden \n Reduction Fishery") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "MenhadenReductionGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')


##Shrimp by Region: Participants
###Northern:
p2mod_ShmpRegPartN <- GAM_predict_p2mod(ShmpRegPartN, mod_ShmpRegPartN)
intercept_ShmpRegPartN = as.numeric(attr(p2mod_ShmpRegPartN,"constant")) 
pdata_ShmpRegPartN <- GAM_predict_pdata(ShmpRegPartN, mod_ShmpRegPartN)
mod.dsig_ShmpRegPartN <- GAM_deriv(pdata_ShmpRegPartN, mod_ShmpRegPartN)
linearMod <- lm(sum_participants ~ year, data= ShmpRegPartN)
summary(linearMod)
dfpost1997_ShmpRegPartN <- filter(ShmpRegPartN, year > 1997)
linearMod_1997 <- lm(sum_participants ~ year, data=dfpost1997_ShmpRegPartN)
summary(linearMod_1997)
both_nonsig(ShmpRegPartN, ShmpRegPartN$sum_participants, intercept_ShmpRegPartN, pdata_ShmpRegPartN, mod.dsig_ShmpRegPartN, "Total Participants", "Year", "Total Participants in Shrimp \n Fishery in Northern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "ShmpRegPartNGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

###Central:
p2mod_ShmpRegPartC <- GAM_predict_p2mod(ShmpRegPartC, mod_ShmpRegPartC)
intercept_ShmpRegPartC = as.numeric(attr(p2mod_ShmpRegPartC,"constant")) 
pdata_ShmpRegPartC <- GAM_predict_pdata(ShmpRegPartC, mod_ShmpRegPartC)
mod.dsig_ShmpRegPartC <- GAM_deriv(pdata_ShmpRegPartC, mod_ShmpRegPartC)
linearMod <- lm(sum_participants ~ year, data= ShmpRegPartC)
summary(linearMod)
dfpost1997_ShmpRegPartC <- filter(ShmpRegPartC, year > 1997)
linearMod_1997 <- lm(sum_participants ~ year, data=dfpost1997_ShmpRegPartC)
summary(linearMod_1997)
both_nonsig(ShmpRegPartC, ShmpRegPartC$sum_participants, intercept_ShmpRegPartC, pdata_ShmpRegPartC, mod.dsig_ShmpRegPartC, "Total Participants", "Year", "Total Participants in Shrimp \n Fishery in Central Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "ShmpRegPartCGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

###Core Banks: 
p2mod_ShmpRegPartCB <- GAM_predict_p2mod(ShmpRegPartCB, mod_ShmpRegPartCB)
intercept_ShmpRegPartCB = as.numeric(attr(p2mod_ShmpRegPartCB,"constant")) 
pdata_ShmpRegPartCB <- GAM_predict_pdata(ShmpRegPartCB, mod_ShmpRegPartCB)
mod.dsig_ShmpRegPartCB <- GAM_deriv(pdata_ShmpRegPartCB, mod_ShmpRegPartCB)
linearMod <- lm(sum_participants ~ year, data= ShmpRegPartCB)
summary(linearMod)
dfpost1997_ShmpRegPartCB <- filter(ShmpRegPartCB, year > 1997)
linearMod_1997 <- lm(sum_participants ~ year, data=dfpost1997_ShmpRegPartCB)
summary(linearMod_1997)
both_sig(ShmpRegPartCB, ShmpRegPartCB$sum_participants, intercept_ShmpRegPartCB, pdata_ShmpRegPartCB, mod.dsig_ShmpRegPartCB, dfpost1997_ShmpRegPartCB, dfpost1997_ShmpRegPartCB$sum_participants, "Total Participants", "Year", "Total Participants in Shrimp \n Fishery in Core Banks Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "ShmpRegPartCBGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Southern: 
p2mod_ShmpRegPartS <- GAM_predict_p2mod(ShmpRegPartS, mod_ShmpRegPartS)
intercept_ShmpRegPartS = as.numeric(attr(p2mod_ShmpRegPartS,"constant")) 
pdata_ShmpRegPartS <- GAM_predict_pdata(ShmpRegPartS, mod_ShmpRegPartS)
mod.dsig_ShmpRegPartS <- GAM_deriv(pdata_ShmpRegPartS, mod_ShmpRegPartS)
linearMod <- lm(sum_participants ~ year, data= ShmpRegPartS)
summary(linearMod)
dfpost1997_ShmpRegPartS <- filter(ShmpRegPartS, year > 1997)
linearMod_1997 <- lm(sum_participants ~ year, data=dfpost1997_ShmpRegPartS)
summary(linearMod_1997)
both_sig(ShmpRegPartS, ShmpRegPartS$sum_participants, intercept_ShmpRegPartS, pdata_ShmpRegPartS, mod.dsig_ShmpRegPartS, dfpost1997_ShmpRegPartS, dfpost1997_ShmpRegPartS$sum_participants, "Total Participants", "Year", "Total Participants in Shrimp \n Fishery in Southern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "ShmpRegPartSGAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Beach Nourishment: Cost
##Northern
p2mod_BeachNourisN <- GAM_predict_p2mod(BeachNourisN, mod_BeachNourisN)
intercept_BeachNourisN = as.numeric(attr(p2mod_BeachNourisN,"constant")) 
pdata_BeachNourisN <- GAM_predict_pdata(BeachNourisN, mod_BeachNourisN)
mod.dsig_BeachNourisN <- GAM_deriv(pdata_BeachNourisN, mod_BeachNourisN)
linearMod <- lm(sum_cost ~ year, data= BeachNourisN)
summary(linearMod)
dfpost1997_BeachNourisN <- filter(BeachNourisN, year > 1997)
linearMod_1997 <- lm(sum_cost ~ year, data=dfpost1997_BeachNourisN)
summary(linearMod_1997)
both_sig(BeachNourisN, BeachNourisN$sum_cost, intercept_BeachNourisN, pdata_BeachNourisN, mod.dsig_BeachNourisN, dfpost1997_BeachNourisN, dfpost1997_BeachNourisN$sum_cost, "Total Cost", "Year", "Total Cost for Beach \n Nourishment in Northern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisN.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Central
p2mod_BeachNourisC <- GAM_predict_p2mod(BeachNourisC, mod_BeachNourisC)
intercept_BeachNourisC = as.numeric(attr(p2mod_BeachNourisC,"constant")) 
pdata_BeachNourisC <- GAM_predict_pdata(BeachNourisC, mod_BeachNourisC)
mod.dsig_BeachNourisC <- GAM_deriv(pdata_BeachNourisC, mod_BeachNourisC)
linearMod <- lm(sum_cost ~ year, data= BeachNourisC)
summary(linearMod)
dfpost1997_BeachNourisC <- filter(BeachNourisC, year > 1997)
linearMod_1997 <- lm(sum_cost ~ year, data=dfpost1997_BeachNourisC)
summary(linearMod_1997)
both_nonsig(BeachNourisC, BeachNourisC$sum_cost, intercept_BeachNourisC, pdata_BeachNourisC, mod.dsig_BeachNourisC, "Total Cost", "Year", "Total Cost for Beach \n Nourishment in Central Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisC.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Southern
p2mod_BeachNourisS <- GAM_predict_p2mod(BeachNourisS, mod_BeachNourisS)
intercept_BeachNourisS = as.numeric(attr(p2mod_BeachNourisS,"constant")) 
pdata_BeachNourisS <- GAM_predict_pdata(BeachNourisS, mod_BeachNourisS)
mod.dsig_BeachNourisS <- GAM_deriv(pdata_BeachNourisS, mod_BeachNourisS)
linearMod <- lm(sum_cost ~ year, data= BeachNourisS)
summary(linearMod)
dfpost1997_BeachNourisS <- filter(BeachNourisS, year > 1997)
linearMod_1997 <- lm(sum_cost ~ year, data=dfpost1997_BeachNourisS)
summary(linearMod_1997)
long_sig(BeachNourisS, BeachNourisS$sum_cost, intercept_BeachNourisS, pdata_BeachNourisS, mod.dsig_BeachNourisS, "Total Cost", "Year", "Total Cost for Beach \n Nourishment in Southern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisS.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Beach Nourishment: Volume
##Northern
p2mod_BeachNourisNvol <- GAM_predict_p2mod(BeachNourisNvol, mod_BeachNourisNvol)
intercept_BeachNourisNvol = as.numeric(attr(p2mod_BeachNourisNvol,"constant")) 
pdata_BeachNourisNvol <- GAM_predict_pdata(BeachNourisNvol, mod_BeachNourisNvol)
mod.dsig_BeachNourisNvol <- GAM_deriv(pdata_BeachNourisNvol, mod_BeachNourisNvol)
linearMod <- lm(sum_vol ~ year, data= BeachNourisNvol)
summary(linearMod)
dfpost1997_BeachNourisNvol <- filter(BeachNourisNvol, year > 1997)
linearMod_1997 <- lm(sum_vol ~ year, data=dfpost1997_BeachNourisNvol)
summary(linearMod_1997)
long_sig(BeachNourisNvol, BeachNourisNvol$sum_cost, intercept_BeachNourisNvol, pdata_BeachNourisNvol, mod.dsig_BeachNourisNvol, "Total Volume", "Year", "Total Volume for Beach \n Nourishment in Northern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisNvol.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Central
p2mod_BeachNourisCvol <- GAM_predict_p2mod(BeachNourisCvol, mod_BeachNourisCvol)
intercept_BeachNourisCvol = as.numeric(attr(p2mod_BeachNourisCvol,"constant")) 
pdata_BeachNourisCvol <- GAM_predict_pdata(BeachNourisCvol, mod_BeachNourisCvol)
mod.dsig_BeachNourisCvol <- GAM_deriv(pdata_BeachNourisCvol, mod_BeachNourisCvol)
linearMod <- lm(sum_vol ~ year, data= BeachNourisCvol)
summary(linearMod)
dfpost1997_BeachNourisCvol <- filter(BeachNourisCvol, year > 1997)
linearMod_1997 <- lm(sum_vol ~ year, data=dfpost1997_BeachNourisCvol)
summary(linearMod_1997)
long_sig(BeachNourisCvol, BeachNourisCvol$sum_cost, intercept_BeachNourisCvol, pdata_BeachNourisCvol, mod.dsig_BeachNourisCvol, "Total Volume", "Year", "Total Volume for Beach \n Nourishment in Central Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisCvol.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Central
p2mod_BeachNourisSvol <- GAM_predict_p2mod(BeachNourisSvol, mod_BeachNourisSvol)
intercept_BeachNourisSvol = as.numeric(attr(p2mod_BeachNourisSvol,"constant")) 
pdata_BeachNourisSvol <- GAM_predict_pdata(BeachNourisSvol, mod_BeachNourisSvol)
mod.dsig_BeachNourisSvol <- GAM_deriv(pdata_BeachNourisSvol, mod_BeachNourisSvol)
linearMod <- lm(sum_vol ~ year, data= BeachNourisSvol)
summary(linearMod)
dfpost1997_BeachNourisSvol <- filter(BeachNourisSvol, year > 1997)
linearMod_1997 <- lm(sum_vol ~ year, data=dfpost1997_BeachNourisSvol)
summary(linearMod_1997)
long_sig(BeachNourisSvol, BeachNourisSvol$sum_cost, intercept_BeachNourisSvol, pdata_BeachNourisSvol, mod.dsig_BeachNourisSvol, "Total Volume", "Year", "Total Volume for Beach \n Nourishment in Southern Region") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("/users/sallydowd/Desktop/Figures/", "BeachNourisSvol.cost.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

#Rec Fishing by Species 

##Gulf flounder
p2mod_RecGK <- GAM_predict_p2mod(RecGK, mod_RecGK)
intercept_RecGK = as.numeric(attr(p2mod_RecGK,"constant")) 
pdata_RecGK <- GAM_predict_pdata(RecGK, mod_RecGK)
mod.dsig_RecGK <- GAM_deriv(pdata_RecGK, mod_RecGK)
linearMod <- lm(Total_harvest ~ year, data= RecGK)
summary(linearMod)
dfpost1997_RecGK <- filter(RecGK, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecGK)
summary(linearMod_1997)
both_sig(RecGK, RecGK$Total_harvest, intercept_RecGK, pdata_RecGK, mod.dsig_RecGK, dfpost1997_RecGK, dfpost1997_RecGK$Total_harvest, "Total Harvest", "Year", "Total Recreational Harvest for \n Gulf Flounder in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecGK.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Red drum
p2mod_RecRD <- GAM_predict_p2mod(RecRD, mod_RecRD)
intercept_RecRD = as.numeric(attr(p2mod_RecRD,"constant")) 
pdata_RecRD <- GAM_predict_pdata(RecRD, mod_RecRD)
mod.dsig_RecRD <- GAM_deriv(pdata_RecRD, mod_RecRD)
linearMod <- lm(Total_harvest ~ year, data= RecRD)
summary(linearMod)
dfpost1997_RecRD <- filter(RecRD, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecRD)
summary(linearMod_1997)
short_sig(RecRD, RecRD$Total_harvest, intercept_RecRD, pdata_RecRD, mod.dsig_RecRD, dfpost1997_RecRD, dfpost1997_RecRD$Total_harvest, "Total Harvest", "Year", "Total Recreational Harvest for \n Red Drum in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecRD.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Red drum modified
p2mod_RecRD.m <- GAM_predict_p2mod(RecRD.m, mod_RecRD.m)
intercept_RecRD.m = as.numeric(attr(p2mod_RecRD.m,"constant")) 
pdata_RecRD.m <- GAM_predict_pdata(RecRD.m, mod_RecRD.m)
mod.dsig_RecRD.m <- GAM_deriv(pdata_RecRD.m, mod_RecRD.m)
linearMod <- lm(Total_harvest ~ year, data= RecRD.m)
summary(linearMod)
dfpost1997_RecRD.m <- filter(RecRD.m, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecRD.m)
summary(linearMod_1997)
both_sig(RecRD.m, RecRD.m$Total_harvest, intercept_RecRD.m, pdata_RecRD.m, mod.dsig_RecRD.m, dfpost1997_RecRD.m, dfpost1997_RecRD.m$Total_harvest, "Total Harvest", "Year", "Total Recreational Harvest for \n Red Drum in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecRD.m.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')


##Sheepshead
p2mod_RecSH <- GAM_predict_p2mod(RecSH, mod_RecSH)
intercept_RecSH = as.numeric(attr(p2mod_RecSH,"constant")) 
pdata_RecSH <- GAM_predict_pdata(RecSH, mod_RecSH)
mod.dsig_RecSH <- GAM_deriv(pdata_RecSH, mod_RecSH)
linearMod <- lm(Total_harvest ~ year, data= RecSH)
summary(linearMod)
dfpost1997_RecSH <- filter(RecSH, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecSH)
summary(linearMod_1997)
long_sig(RecSH, RecSH$Total_harvest, intercept_RecSH, pdata_RecSH, mod.dsig_RecSH, "Total Harvest", "Year", "Total Recreational Harvest for \n Sheepshead in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecSH.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Southern flounder
p2mod_RecSF <- GAM_predict_p2mod(RecSF, mod_RecSF)
intercept_RecSF = as.numeric(attr(p2mod_RecSF,"constant")) 
pdata_RecSF <- GAM_predict_pdata(RecSF, mod_RecSF)
mod.dsig_RecSF <- GAM_deriv(pdata_RecSF, mod_RecSF)
linearMod <- lm(Total_harvest ~ year, data= RecSF)
summary(linearMod)
dfpost1997_RecSF <- filter(RecSF, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecSF)
summary(linearMod_1997)
long_sig(RecSF, RecSF$Total_harvest, intercept_RecSF, pdata_RecSF, mod.dsig_RecSF, "Total Harvest", "Year", "Total Recreational Harvest for \n Southern Flounder in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecSF.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')

##Spotted seatrout 
p2mod_RecSST <- GAM_predict_p2mod(RecSST, mod_RecSST)
intercept_RecSST = as.numeric(attr(p2mod_RecSST,"constant")) 
pdata_RecSST <- GAM_predict_pdata(RecSST, mod_RecSST)
mod.dsig_RecSST <- GAM_deriv(pdata_RecSST, mod_RecSST)
linearMod <- lm(Total_harvest ~ year, data= RecSST)
summary(linearMod)
dfpost1997_RecSST <- filter(RecSST, year > 1997)
linearMod_1997 <- lm(Total_harvest ~ year, data=dfpost1997_RecSST)
summary(linearMod_1997)
long_sig(RecSST, RecSST$Total_harvest, intercept_RecSST, pdata_RecSST, mod.dsig_RecSST, "Total Harvest", "Year", "Total Recreational Harvest for \n Spotted Seatrout in North Carolina") + theme(plot.margin = margin(1,0.75,1,0.75, "cm"))
ggsave(paste0("~/Desktop/", "RecSST.GAMwithTrend.png"), width = 6, height = 4, dpi = 300, units = "in", device='png')
```

